#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Manage/Index.cshtml")]
    public partial class _Views_Manage_Index_cshtml : System.Web.Mvc.WebViewPage<AIT.WebUIComponent.Models.Account.IndexViewModel>
    {
        public _Views_Manage_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Manage\Index.cshtml"
  
    ViewBag.Title = " - ustawienia konta";
    Layout = "~/Views/Shared/_LayoutSubPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <p");

WriteLiteral(" class=\"form-text\"");

WriteLiteral(">\r\n        USTAWIENIA KONTA\r\n    </p>\r\n    <hr");

WriteLiteral(" class=\"separator\"");

WriteLiteral(" />\r\n    <div");

WriteLiteral(" class=\"text-center page-desc\"");

WriteLiteral(">\r\n        <p>\r\n");

WriteLiteral("            ");

            
            #line 14 "..\..\Views\Manage\Index.cshtml"
       Write(ViewBag.StatusMessage);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </p>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-push-3 col-sm-push-2 col-md-6 col-sm-8 col-sm-12 account-settings\"" +
"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n            <tr>\r\n                <td");

WriteLiteral(" class=\"text-right text\"");

WriteLiteral(">\r\n                    Nazwa użytkownika:\r\n                </td>\r\n               " +
" <td");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 26 "..\..\Views\Manage\Index.cshtml"
               Write(Model.Username);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
"");

WriteLiteral(" class=\"text-right text\"");

WriteLiteral(">\r\n                    Hasło:\r\n                </td>\r\n                <td");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n");

            
            #line 34 "..\..\Views\Manage\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\Manage\Index.cshtml"
                     if (Model.HasPassword)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        ");

WriteLiteral("&#9679;&#9679;&#9679;&#9679;&#9679;&#9679;&#9679;&#9679;&#9679;&#9679;\r\n");

            
            #line 37 "..\..\Views\Manage\Index.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n                <td>\r\n");

            
            #line 40 "..\..\Views\Manage\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 40 "..\..\Views\Manage\Index.cshtml"
                     if (Model.HasPassword)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1273), Tuple.Create("\"", 1309)
            
            #line 42 "..\..\Views\Manage\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1280), Tuple.Create<System.Object, System.Int32>(Url.Action("ChangePassword")
            
            #line default
            #line hidden
, 1280), false)
);

WriteLiteral(" class=\"btn-rounded btn-turquoise btn-manage\"");

WriteLiteral(" title=\"Zmień hasło\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"icon icon-lg icon-edit\"");

WriteLiteral("></span>\r\n                        </a>\r\n");

            
            #line 45 "..\..\Views\Manage\Index.cshtml"
                    }
                    else
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1580), Tuple.Create("\"", 1613)
            
            #line 48 "..\..\Views\Manage\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1587), Tuple.Create<System.Object, System.Int32>(Url.Action("SetPassword")
            
            #line default
            #line hidden
, 1587), false)
);

WriteLiteral(" class=\"btn-rounded btn-turquoise btn-manage\"");

WriteLiteral(" title=\"Dodaj hasło\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"icon icon-lg icon-add\"");

WriteLiteral("></span>\r\n                        </a>\r\n");

            
            #line 51 "..\..\Views\Manage\Index.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n            </tr>\r\n            <tr>\r\n                <td");

WriteLiteral(" class=\"text-right text\"");

WriteLiteral(">\r\n                    Adres e-mail:\r\n                </td>\r\n                <td");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 59 "..\..\Views\Manage\Index.cshtml"
               Write(Model.Email);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td>\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2108), Tuple.Create("\"", 2141)
            
            #line 62 "..\..\Views\Manage\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2115), Tuple.Create<System.Object, System.Int32>(Url.Action("ChangeEmail")
            
            #line default
            #line hidden
, 2115), false)
);

WriteLiteral(" class=\"btn-rounded btn-turquoise btn-manage\"");

WriteLiteral(" title=\"Zmień adres e-mail\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"icon icon-lg icon-edit\"");

WriteLiteral("></span>\r\n                    </a>\r\n                </td>\r\n            </tr>\r\n   " +
"         <tr>\r\n");

            
            #line 68 "..\..\Views\Manage\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 68 "..\..\Views\Manage\Index.cshtml"
                 if (Model.LoginsCount > 0)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-right text\"");

WriteLiteral(">\r\n                        Połączono z\r\n                    </td>\r\n");

WriteLiteral("                    <td");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 74 "..\..\Views\Manage\Index.cshtml"
                   Write(Model.LoginsCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 75 "..\..\Views\Manage\Index.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 75 "..\..\Views\Manage\Index.cshtml"
                         if (Model.LoginsCount == 1)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            ");

WriteLiteral("&nbsp;zewnętrznym kontem\r\n");

            
            #line 78 "..\..\Views\Manage\Index.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            ");

WriteLiteral("&nbsp;zewnętrznymi kontami\r\n");

            
            #line 82 "..\..\Views\Manage\Index.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </td>\r\n");

WriteLiteral("                    <td>\r\n                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3019), Tuple.Create("\"", 3053)
            
            #line 85 "..\..\Views\Manage\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3026), Tuple.Create<System.Object, System.Int32>(Url.Action("ManageLogins")
            
            #line default
            #line hidden
, 3026), false)
);

WriteLiteral(" class=\"btn-rounded btn-turquoise btn-manage\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"icon icon-lg icon-edit\"");

WriteLiteral("></span>\r\n                        </a>\r\n                    </td>\r\n");

            
            #line 89 "..\..\Views\Manage\Index.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(" class=\"text-center text\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 93 "..\..\Views\Manage\Index.cshtml"
                   Write(Html.ActionLink("Połącz z zewnętrznym kontem", "ManageLogins"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n");

            
            #line 95 "..\..\Views\Manage\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n        </table>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
