#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    #line 2 "..\..\Views\Manage\ManageLogins.cshtml"
    using Microsoft.Owin.Security;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Manage/ManageLogins.cshtml")]
    public partial class _Views_Manage_ManageLogins_cshtml : System.Web.Mvc.WebViewPage<AIT.WebUIComponent.Models.Account.ManageLoginsViewModel>
    {
        public _Views_Manage_ManageLogins_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Manage\ManageLogins.cshtml"
  
    ViewBag.Title = " - zewnętrzne konta";
    Layout = "~/Views/Shared/_LayoutSubPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <p");

WriteLiteral(" class=\"form-text\"");

WriteLiteral(">\r\n        ZEWNĘTRZNE KONTA\r\n    </p>\r\n    <hr");

WriteLiteral(" class=\"separator\"");

WriteLiteral(" />\r\n    <div");

WriteLiteral(" class=\"text-center page-desc\"");

WriteLiteral(">\r\n        <p>\r\n");

WriteLiteral("            ");

            
            #line 16 "..\..\Views\Manage\ManageLogins.cshtml"
       Write(ViewBag.StatusMessage);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </p>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-push-4 col-md-4 col-sm-push-3 col-sm-6 col-xs-12 ex-services\"");

WriteLiteral(">\r\n");

            
            #line 22 "..\..\Views\Manage\ManageLogins.cshtml"
        
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Manage\ManageLogins.cshtml"
          
            var loginProviders = Context.GetOwinContext().Authentication.GetExternalAuthenticationTypes();

            if (Model.CurrentLogins.Count > 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <h4>Powiązane konta:</h4>\r\n");

WriteLiteral("                <table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n                    <tbody>\r\n");

            
            #line 30 "..\..\Views\Manage\ManageLogins.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Manage\ManageLogins.cshtml"
                         foreach (var account in Model.CurrentLogins)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <tr>\r\n                                <td");

WriteLiteral(" class=\"text\"");

WriteLiteral(">");

            
            #line 33 "..\..\Views\Manage\ManageLogins.cshtml"
                                            Write(account.LoginProvider);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>\r\n");

            
            #line 35 "..\..\Views\Manage\ManageLogins.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\Manage\ManageLogins.cshtml"
                                     if (ViewBag.ShowRemoveButton)
                                    {
                                        using (Html.BeginForm("RemoveLogin", "Manage"))
                                        {
                                            
            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\Manage\ManageLogins.cshtml"
                                       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\Manage\ManageLogins.cshtml"
                                                                    

            
            #line default
            #line hidden
WriteLiteral("                                            <div");

WriteLiteral(" class=\"delete-ex-login\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                ");

            
            #line 41 "..\..\Views\Manage\ManageLogins.cshtml"
                                           Write(Html.Hidden("loginProvider", account.LoginProvider));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                                ");

            
            #line 42 "..\..\Views\Manage\ManageLogins.cshtml"
                                           Write(Html.Hidden("providerKey", account.ProviderKey));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn-rounded btn-dismiss\"");

WriteLiteral(">\r\n                                                    <span");

WriteLiteral(" class=\"icon icon-lg icon-trash\"");

WriteLiteral("></span>\r\n                                                </button>\r\n            " +
"                                </div>\r\n");

            
            #line 47 "..\..\Views\Manage\ManageLogins.cshtml"
                                        }
                                    }
                                    else
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        ");

WriteLiteral(" &nbsp;\r\n");

            
            #line 52 "..\..\Views\Manage\ManageLogins.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </td>\r\n                            </tr>\r\n");

            
            #line 55 "..\..\Views\Manage\ManageLogins.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n                </table>\r\n");

            
            #line 58 "..\..\Views\Manage\ManageLogins.cshtml"
            }
            if (Model.OtherLogins.Count > 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <h4>Dodaj możliwość logowania z konta:</h4>\r\n");

            
            #line 62 "..\..\Views\Manage\ManageLogins.cshtml"
                using (Html.BeginForm("LinkLogin", "Manage"))
                {
                    
            
            #line default
            #line hidden
            
            #line 64 "..\..\Views\Manage\ManageLogins.cshtml"
               Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 64 "..\..\Views\Manage\ManageLogins.cshtml"
                                            

            
            #line default
            #line hidden
WriteLiteral("                    <table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n                        <tbody>\r\n");

            
            #line 67 "..\..\Views\Manage\ManageLogins.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\Manage\ManageLogins.cshtml"
                             foreach (AuthenticationDescription p in Model.OtherLogins)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <tr>\r\n                                    <td");

WriteLiteral(" class=\"text\"");

WriteLiteral(">");

            
            #line 70 "..\..\Views\Manage\ManageLogins.cshtml"
                                                Write(p.AuthenticationType);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                    <td>\r\n                                " +
"        <div");

WriteLiteral(" class=\"add-ex-login\"");

WriteLiteral(">\r\n                                            <button");

WriteLiteral(" class=\"btn-rounded btn-turquoise\"");

WriteAttribute("id", Tuple.Create(" id=\"", 3174), Tuple.Create("\"", 3200)
            
            #line 73 "..\..\Views\Manage\ManageLogins.cshtml"
          , Tuple.Create(Tuple.Create("", 3179), Tuple.Create<System.Object, System.Int32>(p.AuthenticationType
            
            #line default
            #line hidden
, 3179), false)
);

WriteLiteral(" name=\"provider\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3217), Tuple.Create("\"", 3246)
            
            #line 73 "..\..\Views\Manage\ManageLogins.cshtml"
                                                        , Tuple.Create(Tuple.Create("", 3225), Tuple.Create<System.Object, System.Int32>(p.AuthenticationType
            
            #line default
            #line hidden
, 3225), false)
);

WriteLiteral(">\r\n                                                <span");

WriteLiteral(" class=\"icon icon-lg icon-add\"");

WriteLiteral("></span>\r\n                                            </button>\r\n                " +
"                        </div>\r\n                                    </td>\r\n     " +
"                           </tr>\r\n");

            
            #line 79 "..\..\Views\Manage\ManageLogins.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </tbody>\r\n                    </table>\r\n");

            
            #line 82 "..\..\Views\Manage\ManageLogins.cshtml"
                }
            }
        
            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
