#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Login.cshtml")]
    public partial class _Views_Shared__Login_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Login_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"navbar-collapse collapse\"");

WriteLiteral(" id=\"navbarUserOptions\"");

WriteLiteral(">\r\n    <ul");

WriteLiteral(" class=\"nav navbar-nav navbar-right navbar-login\"");

WriteLiteral(">\r\n");

            
            #line 3 "..\..\Views\Shared\_Login.cshtml"
        
            
            #line default
            #line hidden
            
            #line 3 "..\..\Views\Shared\_Login.cshtml"
         if (Request.IsAuthenticated)
        {
            

            
            #line default
            #line hidden
WriteLiteral("            <li");

WriteLiteral(" class=\"nav\"");

WriteLiteral(">");

            
            #line 6 "..\..\Views\Shared\_Login.cshtml"
                       Write(Html.ActionLink("ZARZĄDZAJ KONTEM", "Index", "Manage"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

WriteLiteral("            <li");

WriteLiteral(" class=\"nav\"");

WriteLiteral(">\r\n");

            
            #line 8 "..\..\Views\Shared\_Login.cshtml"
                
            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Shared\_Login.cshtml"
                 using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                {
                    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Shared\_Login.cshtml"
               Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Shared\_Login.cshtml"
                                            

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteLiteral(" id=\"btnLogOut\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">WYLOGUJ</a>\r\n");

            
            #line 12 "..\..\Views\Shared\_Login.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </li>\r\n");

            
            #line 14 "..\..\Views\Shared\_Login.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <li");

WriteLiteral(" class=\"nav\"");

WriteLiteral(">");

            
            #line 17 "..\..\Views\Shared\_Login.cshtml"
                       Write(Html.ActionLink("REJESTRACJA", "Register", "Account"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

WriteLiteral("            <li");

WriteLiteral(" class=\"nav\"");

WriteLiteral(">");

            
            #line 18 "..\..\Views\Shared\_Login.cshtml"
                       Write(Html.ActionLink("LOGOWANIE", "Login", "Account", new { returnUrl = "/Home" }, null));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

            
            #line 19 "..\..\Views\Shared\_Login.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </ul>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
