#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_ModalAnimate.cshtml")]
    public partial class _Views_Shared__ModalAnimate_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__ModalAnimate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal fade animate-modal\"");

WriteAttribute("id", Tuple.Create(" id=\"", 39), Tuple.Create("\"", 59)
            
            #line 2 "..\..\Views\Shared\_ModalAnimate.cshtml"
, Tuple.Create(Tuple.Create("", 44), Tuple.Create<System.Object, System.Int32>(ViewData["Id"]
            
            #line default
            #line hidden
, 44), false)
);

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"lblAnimateModalDesc\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog modal-sm\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n");

            
            #line 5 "..\..\Views\Shared\_ModalAnimate.cshtml"
            
            
            #line default
            #line hidden
            
            #line 5 "..\..\Views\Shared\_ModalAnimate.cshtml"
             using (Ajax.BeginForm(ViewData["Action"].ToString(), ViewData["Controller"].ToString(), null, new AjaxOptions
            {
                OnBegin = "dialogAnimation.begin",
                OnSuccess = "dialogAnimation.success",
                OnFailure = "dialogAnimation.error"
            }, new { autocomplete = "off" }))
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn-rounded btn-small btn-dismiss right\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"icon icon-sm icon-cancel\"");

WriteLiteral("></span>\r\n                    </button>\r\n                    <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" id=\"lblAnimateModalDesc\"");

WriteLiteral(">");

            
            #line 16 "..\..\Views\Shared\_ModalAnimate.cshtml"
                                                                Write(ViewData["Desc"]);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-1\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn-rounded btn-small btn-turquoise btn-anim-modal-prev disabled\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" title=\"Poprzedni\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"icon icon-sm icon-left\"");

WriteLiteral("></span>\r\n                            </button>\r\n                        </div>\r\n" +
"                        <div");

WriteLiteral(" class=\"col-xs-10\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"modal-body-content\"");

WriteLiteral(">\r\n                                ");

WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"             <div");

WriteLiteral(" class=\"col-xs-1\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn-rounded btn-small btn-turquoise btn-anim-modal-next disabled\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" title=\"Następny\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"icon icon-sm icon-right\"");

WriteLiteral("></span>\r\n                            </button>\r\n                        </div>\r\n" +
"                    </div>\r\n                    <div");

WriteLiteral(" class=\"row text-center\"");

WriteLiteral(">\r\n                        <hr");

WriteLiteral(" class=\"separator\"");

WriteLiteral(" />\r\n                        <div");

WriteLiteral(" class=\"col-xs-10 col-xs-offset-1\"");

WriteLiteral(">\r\n                            <ol");

WriteLiteral(" class=\"items-indicators\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral("></ol>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-xs-1\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn-rounded btn-small btn-turquoise btn-anim-modal-del-last\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" title=\"Usuń\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"icon icon-sm icon-trash\"");

WriteLiteral("></span>\r\n                            </button>\r\n                        </div>\r\n" +
"                    </div>\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn-rounded btn-turquoise disabled\"");

WriteLiteral(" title=\"Zapisz\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"icon icon-lg icon-save\"");

WriteLiteral("></span>\r\n                    </button>\r\n                </div>\r\n");

            
            #line 53 "..\..\Views\Shared\_ModalAnimate.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
