#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_PdfLayout.cshtml")]
    public partial class _Views_Shared__PdfLayout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__PdfLayout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_PdfLayout.cshtml"
  
    Layout = null;
    var imagePath = Server.MapPath("~/Images");

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n    <title>");

            
            #line 10 "..\..\Views\Shared\_PdfLayout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(@"</title>
    <style>        
        table {
            width: 100%;
            border-spacing: 0px;
            margin-bottom: 15px;
        }

        table thead tr th {
            font-size: 16px;
            padding: 15px;
        }

        table tbody tr td {
            font-size: 14px;
            border: 1px solid #ddd;
            border-left-color: white;
            border-right-color: white;
            border-top-color: white;
            padding: 8px 15px;
        }

        .clear-border {
            border-bottom-color: white;
        }
    </style>
</head>
<body>
    <p>
        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 837), Tuple.Create("\"", 868)
            
            #line 39 "..\..\Views\Shared\_PdfLayout.cshtml"
, Tuple.Create(Tuple.Create("", 843), Tuple.Create<System.Object, System.Int32>(imagePath
            
            #line default
            #line hidden
, 843), false)
, Tuple.Create(Tuple.Create("", 853), Tuple.Create("/logo_small.png", 853), true)
);

WriteLiteral(" />\r\n    </p>\r\n    <div>\r\n");

WriteLiteral("        ");

            
            #line 42 "..\..\Views\Shared\_PdfLayout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
