#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Search.cshtml")]
    public partial class _Views_Shared__Search_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Search_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"search-area\"");

WriteLiteral(">\r\n    <input");

WriteLiteral(" id=\"txtSearch\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" placeholder=\"Wyszukaj\"");

WriteLiteral(" />\r\n    <button");

WriteLiteral(" id=\"btnSearch\"");

WriteLiteral(" class=\"btn-rounded btn-turquoise noevent\"");

WriteLiteral(" title=\"Wyczyść pole wyszukiwania\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"icon icon-lg icon-search\"");

WriteLiteral("></span>\r\n    </button>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
