#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Ballroom\_BallroomItems.cshtml"
    using AIT.BallroomDomain.Model.Enums;
    
    #line default
    #line hidden
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Ballroom/_BallroomItems.cshtml")]
    public partial class _Views_Ballroom__BallroomItems_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Ballroom__BallroomItems_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"ballroom-items\"");

WriteLiteral(">\r\n    <div>\r\n        <button");

WriteLiteral(" class=\"btn-rounded btn-turquoise\"");

WriteLiteral(" data-item-type=\"");

            
            #line 5 "..\..\Views\Ballroom\_BallroomItems.cshtml"
                                                              Write((int)ItemType.TableRect);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"icon-ballroom icon-tab-rect\"");

WriteLiteral("></span>\r\n        </button>\r\n    </div>\r\n    <div>\r\n        <button");

WriteLiteral(" class=\"btn-rounded btn-turquoise\"");

WriteLiteral(" data-item-type=\"");

            
            #line 10 "..\..\Views\Ballroom\_BallroomItems.cshtml"
                                                              Write((int)ItemType.TableRound);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"icon-ballroom icon-tab-round\"");

WriteLiteral("></span>\r\n        </button>\r\n    </div>\r\n    <div>\r\n        <button");

WriteLiteral(" class=\"btn-rounded btn-turquoise\"");

WriteLiteral(" data-item-type=\"");

            
            #line 15 "..\..\Views\Ballroom\_BallroomItems.cshtml"
                                                              Write((int)ItemType.StageRect);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"icon-ballroom icon-stage-rect\"");

WriteLiteral("></span>\r\n        </button>\r\n    </div>\r\n    <div>\r\n        <button");

WriteLiteral(" class=\"btn-rounded btn-turquoise\"");

WriteLiteral(" data-item-type=\"");

            
            #line 20 "..\..\Views\Ballroom\_BallroomItems.cshtml"
                                                              Write((int)ItemType.StageHalfCircle);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"icon-ballroom icon-stage-round\"");

WriteLiteral("></span>\r\n        </button>\r\n    </div>\r\n    <div>\r\n        <button");

WriteLiteral(" class=\"btn-rounded btn-turquoise\"");

WriteLiteral(" data-item-type=\"");

            
            #line 25 "..\..\Views\Ballroom\_BallroomItems.cshtml"
                                                              Write((int)ItemType.PillarRect);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"icon-ballroom icon-pillar-rect\"");

WriteLiteral("></span>\r\n        </button>\r\n    </div>\r\n    <div>\r\n        <button");

WriteLiteral(" class=\"btn-rounded btn-turquoise\"");

WriteLiteral(" data-item-type=\"");

            
            #line 30 "..\..\Views\Ballroom\_BallroomItems.cshtml"
                                                              Write((int)ItemType.PillarRound);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"icon-ballroom icon-pillar-round\"");

WriteLiteral("></span>\r\n        </button>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
