#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Ballroom/Index.cshtml")]
    public partial class _Views_Ballroom_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Ballroom_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Ballroom\Index.cshtml"
  
    ViewBag.Title = " - sala weselna";
    Layout = "~/Views/Shared/_LayoutSubPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" id=\"ballroomContainer\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"switch-display ballroom hidden-xs hidden-sm\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn-rounded btn-small btn-blue\"");

WriteLiteral(" id=\"btnToggleLayout\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"icon icon-sm icon-left\"");

WriteLiteral("></span>\r\n        </button>\r\n    </div>   \r\n    <div");

WriteLiteral(" class=\"row hidden-xs\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ballroom-panel\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ballroom-btns-area\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" id=\"btnBallroomItems\"");

WriteLiteral(" class=\"btn-rounded btn-turquoise nohover\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"icon icon-lg icon-items\"");

WriteLiteral("></span>\r\n                </button>\r\n                <button");

WriteLiteral(" id=\"btnSaveLayout\"");

WriteLiteral(" class=\"btn-rounded btn-turquoise disabled\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"icon icon-lg icon-save\"");

WriteLiteral("></span>\r\n                </button>                \r\n");

            
            #line 21 "..\..\Views\Ballroom\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Ballroom\Index.cshtml"
                   Html.RenderPartial("_BallroomItems"); 
            
            #line default
            #line hidden
WriteLiteral("                \r\n            </div>\r\n            <div");

WriteLiteral(" class=\"guests-panel-action\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" id=\"btnPersonsPanel\"");

WriteLiteral(" class=\"btn-rounded btn-turquoise nohover\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"icon-ballroom icon-guests\"");

WriteLiteral("></span>\r\n                </button>\r\n            </div>\r\n        </div>\r\n    </di" +
"v>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"guests-panel\"");

WriteLiteral(">            \r\n            <div");

WriteLiteral(" id=\"guests\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"list-group ballroom-couple\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" pid=\"bride\"");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"list-item-content\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"ballroom-guest-content\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"ballroom-guest bride\"");

WriteLiteral(">Panna młoda</div>\r\n                            </div>\r\n                         " +
"   <div");

WriteLiteral(" class=\"list-item-handle\"");

WriteLiteral("></div>\r\n                        </div>\r\n                    </li>\r\n             " +
"       <li");

WriteLiteral(" pid=\"groom\"");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"list-item-content\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"ballroom-guest-content\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"ballroom-guest groom\"");

WriteLiteral(">Pan młody</div>\r\n                            </div>\r\n                           " +
" <div");

WriteLiteral(" class=\"list-item-handle\"");

WriteLiteral("></div>\r\n                        </div>\r\n                    </li>\r\n             " +
"   </ul>\r\n                ");

WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"layout-container\"");

WriteLiteral(" id=\"layoutContainer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"layout-content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ballroom-layout narrow\"");

WriteLiteral(" id=\"ballroomLayout\"");

WriteLiteral(">\r\n\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"layout-change narrow-v hidden-xs\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn-rounded btn-small btn-turquoise btn-layout\"");

WriteLiteral(" name=\"narrowV\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"icon icon-sm icon-narrow-v\"");

WriteLiteral("></span>\r\n                </button>\r\n            </div>            \r\n            " +
"<div");

WriteLiteral(" class=\"layout-change narrow-h hidden-xs\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn-rounded btn-small btn-turquoise btn-layout\"");

WriteLiteral(" name=\"narrowH\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"icon icon-sm icon-narrow-h\"");

WriteLiteral("></span>\r\n                </button>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"layout-change expand-layout hidden-xs\"");

WriteLiteral(" id=\"expandLayoutBtns\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn-rounded btn-small btn-turquoise btn-layout\"");

WriteLiteral(" name=\"expandV\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"icon icon-sm icon-expand-v\"");

WriteLiteral("></span>\r\n                </button>                \r\n                <button");

WriteLiteral(" class=\"btn-rounded btn-small btn-turquoise btn-layout\"");

WriteLiteral(" name=\"expandH\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"icon icon-sm icon-expand-h\"");

WriteLiteral("></span>\r\n                </button>\r\n            </div>\r\n        </div>\r\n    </di" +
"v>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 83 "..\..\Views\Ballroom\Index.cshtml"
Write(Scripts.Render("~/bundles/ballroom"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
