#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Documents/PrivacyAndCookiesPolicy.cshtml")]
    public partial class _Views_Documents_PrivacyAndCookiesPolicy_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Documents_PrivacyAndCookiesPolicy_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Documents\PrivacyAndCookiesPolicy.cshtml"
  
    ViewBag.Title = " - polityka prywatności i plików cookies";
    Layout = "~/Views/Shared/_LayoutSubPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<div");

WriteLiteral(" class=\"regulations-area\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"reulations-download\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 9 "..\..\Views\Documents\PrivacyAndCookiesPolicy.cshtml"
   Write(Html.ActionLink("Pobierz Politykę prywatności i plików cookies w formie PDF", "GetPrivacyAndCookiesPolicy", "Documents"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div>\r\n<pre");

WriteLiteral(" class=\"regulations\"");

WriteLiteral(">\r\n        <strong>POLITYKA PRYWATNOŚCI I PLIKÓW „COOKIES”</strong>\r\n\r\nNiniejszy " +
"dokument reguluje Politykę prywatności i plików „cookies” Serwisu internetowego " +
"prowadzonego w domenie Zamiłowani.pl (zwanego dalej Serwisem). Robert Wąsik (zwa" +
"ny dalej Usługodawcą) dochowuje wszelkiej należytej staranności w celu poszanowa" +
"nia prywatności użytkowników Serwisu.\r\n\r\n<strong>Administrator</strong>\r\nAdminis" +
"tratorem danych zawartych w Serwisie internetowym Zamiłowani.pl jest Robert Wąsi" +
"k, ul. Strońska 3J, 50-540 Wrocław, adres e-mail: kontakt@zamilowani.pl.\r\n\r\n<str" +
"ong>Dane osobowe</strong>\r\nUżytkowników korzystających z Usług świadczonych drog" +
"ą elektroniczną za pośrednictwem Serwisu prosimy o dobrowolne podanie danych oso" +
"bowych, obejmujących w szczególności nazwę mogącą być imieniem i nazwiskiem oraz" +
" adres e-mail. Dane te mogą zostać zebrane, również jeśli jest to konieczne do r" +
"ealizacji umowy, gdy osoba, której dane dotyczą, jest jej stroną lub gdy jest to" +
" niezbędne do podjęcia działań przed zawarciem umowy na żądanie osoby, której da" +
"ne dotyczą. W/w dane zostają przez nas zebrane w celu świadczenia Usług na rzecz" +
" osób których dotyczą. Odbiorcą zebranych danych jest wyłącznie Usługodawca.\r\n\r\n" +
"Możemy również zwracać się do użytkowników korzystających z Usług świadczonych d" +
"rogą elektroniczną za pośrednictwem Serwisu z prośbą o dobrowolne podanie danych" +
" osobowych, obejmujących w szczególności imię, nazwisko, adres, adres e-mail, nu" +
"mer telefonu w celach marketingowych. Cele te mogą obejmować w szczególności prz" +
"esłanie przez Usługodawcę informacji handlowych przy użyciu danych kontaktowych " +
"Użytkownika. Zgoda na przetwarzanie danych w tym zakresie może być cofnięta w ka" +
"żdej chwili.\r\n\r\nAdministrator danych dochowuje szczególnej i należytej starannoś" +
"ci w celu ochrony praw Użytkowników, których dane podlegają przetwarzaniu, a w s" +
"zczególności zapewnia, aby dane te były:\r\n•\tprzetwarzane zgodnie z prawem,\r\n•\tzb" +
"ierane dla oznaczonych w niniejszym dokumencie i zgodnych z prawem celów,\r\n•\tnie" +
" poddawane dalszemu przetwarzaniu niezgodnemu z powyższymi celami,\r\n•\tmerytorycz" +
"nie poprawne i adekwatne w stosunku do celów, w jakich są przetwarzane,\r\n•\tprzec" +
"howywane w postaci umożliwiającej identyfikację osób, których dotyczą, nie dłuże" +
"j niż jest to niezbędne do osiągnięcia celu przetwarzania. \r\n\r\nUżytkownikom przy" +
"sługuje prawo kontroli przetwarzania danych, które ich dotyczą, zawartych w zbio" +
"rach danych Usługodawcy. Jest to zwłaszcza prawo do dostępu do treści swoich dan" +
"ych oraz ich poprawiania, a także żądania uzupełnienia, uaktualnienia, sprostowa" +
"nia danych osobowych, czasowego lub stałego wstrzymania ich przetwarzania lub ic" +
"h usunięcia, jeżeli są one niekompletne, nieaktualne, nieprawdziwe lub zostały z" +
"ebrane z naruszeniem ustawy albo są już zbędne do realizacji celu, dla którego z" +
"ostały zebrane.\r\n\r\n<strong>Dzienniki systemowe</strong>\r\nTo wewnętrzne dzienniki" +
" zdarzeń serwera Serwisu, automatycznie zapisujące żądania stron wysyłane, gdy u" +
"żytkownicy odwiedzają jego witryny. Dzienniki systemowe zawierają żądanie strony" +
" wysłane przez użytkownika, adres IP, typ przeglądarki, język przeglądarki, datę" +
" i godzinę żądania oraz co najmniej jeden plik „cookie”, który może jednoznaczni" +
"e identyfikować przeglądarkę użytkownika. \r\n\r\n<strong>Plik „cookie”</strong>\r\nJe" +
"st niewielkim plikiem zawierającym ciąg znaków, który jest wysyłany do komputera" +
" użytkownika podczas odwiedzania przez niego Serwisu. Gdy użytkownik odwiedza Se" +
"rwis ponownie, dzięki plikowi „cookie” przeglądarka użytkownika może zostać rozp" +
"oznana przez Serwis. W ustawieniach przeglądarki można wybrać opcję odrzucania p" +
"lików „cookie” lub sygnalizowania, że taki plik został przesłany. Użytkownik Ser" +
"wisu może wyrazić zgodę na korzystanie z plików „cookie”. Bez nich, niektóre fun" +
"kcjonalności Serwisu mogą jednak nie działać poprawnie.\r\n\r\n<strong>Gromadzenie d" +
"anych</strong>\r\nDane gromadzone w dziennikach systemowych są wykorzystywane prze" +
"z Usługodawcę przez czas nieokreślony wyłącznie w celu administrowania Serwisem." +
" Nie są one przekazywane na rzecz podmiotów trzecich, z wyłączeniem okoliczności" +
" opisanych w niniejszym dokumencie.\r\n\r\nW związku z korzystaniem z Serwisu przez " +
"użytkowników, w sposób automatyczny możemy zbierać i zapisywać w dziennikach ser" +
"werów szczegóły techniczne dotyczące sposobu korzystania z Usług, przesłane prze" +
"z użytkownika żądania związane ze świadczeniem usług drogą elektroniczną, adres " +
"IP oraz dane techniczne o działaniu Serwisu w związku z czynnościami dokonywanym" +
"i przez użytkownika, w szczególności informacje o rozpoczęciu, zakończeniu oraz " +
"zakresie każdorazowego korzystania z Usługi świadczonej drogą elektroniczną. Moż" +
"emy również zbierać informacje, celem przechowywania ich lokalnie na urządzeniu " +
"użytkownika, korzystając z mechanizmu pamięci przeglądarki. \r\n\r\nW trakcie świadc" +
"zenia Usług na rzecz użytkowników, stosujemy profesjonalne technologie do gromad" +
"zenia i zapisywania informacji, takie jak pliki „cookie”. Dostęp do danych „cook" +
"ie” może posiadać również firma Google za pośrednictwem narzędzi Google Analytic" +
"s oraz Google Adwords, w celu sporządzenia statystyk ruchu oraz skuteczności kam" +
"panii promocyjnych realizowanych przez Usługodawcę za pomocą wyżej wymienionych " +
"narzędzi.\r\n\r\nDane zgromadzone w Serwisie zgromadzone są na zewnętrznych bezpiecz" +
"nych i profesjonalnych serwerach, na podstawie umów zawartych przez Usługodawcę." +
" Usługodawca dochowuje należytych środków ostrożności, celem zabezpieczenia dany" +
"ch osobowych użytkowników przed dostępem osób nieuprawnionych, zniszczeniem, uja" +
"wnieniem oraz bezprawnym wykorzystaniem. Do przetwarzania danych użytkowników Se" +
"rwisu uprawnieni są wyłącznie sami użytkownicy, Usługodawca oraz wskazane w nini" +
"ejszym dokumencie podmioty trzecie w celach statystycznych.\r\n\r\n<strong>Inne</str" +
"ong>\r\nSerwis może zawierać odnośniki do innych stron internetowych. Nie ponosimy" +
" odpowiedzialności za obowiązujące na tych stronach zasady przestrzegania polity" +
"ki prywatności. Zalecamy zapoznania się z polityką prywatności tych stron po wej" +
"ściu na nie. \r\n\r\nUsługodawca zastrzega prawo do zmiany Polityki prywatności i pl" +
"ików „cookies”.\r\n\r\n\r\nNiniejszy dokument stanowi załącznik do Regulaminu świadcze" +
"nia usług drogą elektroniczną przez Zamiłowani.pl\r\n</pre>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
