#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Documents/UserAgreement.cshtml")]
    public partial class _Views_Documents_UserAgreement_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Documents_UserAgreement_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Documents\UserAgreement.cshtml"
  
    ViewBag.Title = " - regulamin";
    Layout = "~/Views/Shared/_LayoutSubPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"regulations-area\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"reulations-download\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 8 "..\..\Views\Documents\UserAgreement.cshtml"
   Write(Html.ActionLink("Pobierz Regulamin serwisu w formie PDF", "GetUserAgreement", "Documents"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div>\r\n<pre");

WriteLiteral(" class=\"regulations\"");

WriteLiteral(">\r\n        <strong>REGULAMIN ŚWIADCZENIA USŁUG DROGĄ ELEKTRONICZNĄ</strong>\r\n\r\n  " +
"      <strong>Postanowienia wstępne</strong>\r\n1.\t<strong>Regulamin</strong> to n" +
"iniejszy Regulamin świadczenia usług drogą elektroniczną w obszarze domeny inter" +
"netowej Zamiłowani.pl, który określa warunki świadczenia Usług przez Usługodawcę" +
" za pośrednictwem witryny www.Zamiłowani.pl na rzecz Użytkowników.\r\n2.\t<strong>U" +
"żytkownik</strong> to podmiot, który zawiera ze Usługodawcą umowę o świadczenie " +
"Usługi, pod warunkiem posiadania pełnej zdolności do czynności prawnych, lub ogr" +
"aniczonej zdolności do czynności prawnych w przypadkach uregulowanych przepisami" +
" prawa powszechnie obowiązującego albo bycia osobą prawną lub jednostką organiza" +
"cyjną.\r\n3.\t<strong>Konsument</strong> to Użytkownik, który jest osobą fizyczną i" +
" zawiera umowę niezwiązaną bezpośrednio z prowadzoną przez niego działalnością g" +
"ospodarczą lub zawodową.\r\n4.\t<strong>Usługodawca</strong> to Robert Wąsik, ul. S" +
"trońska 8/3J, 50-540 Wrocław, będący Usługodawcą, administratorem i właścicielem" +
" Serwisu.\r\n5.\t<strong>Serwis</strong> to serwis internetowy prowadzony przez Usł" +
"ugodawcę w języku polskim za pośrednictwem witryny www dostępnej w sieci Interne" +
"t pod adresem url www.Zamiłowani.pl.\r\n6.\t<strong>Usługa</strong> to usługa prowa" +
"dzenia Konta Klienta świadczona przez Usługodawcę na rzecz Użytkownika, na podst" +
"awie umowy zawartej pomiędzy stronami za pośrednictwem Serwisu, w ramach zorgani" +
"zowanego systemu zawierania umów na odległość, bez jednoczesnej fizycznej obecno" +
"ści stron. \r\n7.\t<strong>Dane Kontaktowe Usługodawcy</strong> to dane Usługodawcy" +
", przy użyciu których Użytkownik może się z nim skontaktować, tj. Robert Wąsik, " +
"ul. Strońska 8/3J, 50-540 Wrocław, adres e-mail: kontakt@zamilowani.pl.\r\n8.\t<str" +
"ong>Dane Kontaktowe Użytkownika</strong> to dane Użytkownika, przy użyciu któryc" +
"h Usługodawca może skontaktować się z Użytkownikiem, obejmujące adres poczty ele" +
"ktronicznej i jego nazwę.\r\n9.\t<strong>Konto Użytkownika</strong> to panel zarząd" +
"zający zamówieniami Użytkownika i Usługami świadczonymi na jego rzecz, dostępny " +
"w obszarze Serwisu, pod warunkiem Rejestracji lub Logowania. \r\n10.\t<strong>Rejes" +
"tracja</strong> to utworzenie Konta Użytkownika przez Użytkownika, przy użyciu f" +
"ormularza rejestracyjnego Serwisu znajdującego się na jego stronie internetowej." +
"\r\n11.\t<strong>Logowanie</strong> to proces uwierzytelnienia i autoryzacji Użytko" +
"wnika, polegający na podaniu nazwy Użytkownika oraz hasła uwierzytelniającego w " +
"celu uzyskania dostępu do Konta Użytkownika. Logowanie może następować również p" +
"rzy użyciu zewnętrznych kont Użytkownika: Microsoft, Facebook lub Google.\r\n\r\n<st" +
"rong>§1 Ogólne warunki umowne</strong>\r\n1.\tUsługodawca na podstawie art. 8 ust. " +
"1 pkt 1 ustawy z dnia 18 lipca 2002 r. o świadczeniu usług drogą elektroniczną u" +
"stanawia Regulamin, który udostępnia pod adresem url Serwisu, w brzmieniu: www.Z" +
"amiłowani.pl\r\n2.\tUsługodawca świadczy Usługi zgodnie z Regulaminem i przepisami " +
"powszechnie obowiązującego prawa.\r\n3.\tUsługodawca udostępnia niniejszy Regulamin" +
" na stronie internetowej Serwisu. \r\n4.\tUżytkownicy mogą w dowolnym czasie: uzysk" +
"ać dostęp do Regulaminu, utrwalić go, pozyskać i odtworzyć poprzez wydrukowanie " +
"lub zapisanie na nośniku danych.\r\n5.\tŚwiadczenie Usług odbywa się za pośrednictw" +
"em strony internetowej Serwisu przez 24 godziny na dobę i 7 dni w tygodniu.\r\n6.\t" +
"W celu korzystania z Serwisu konieczne jest dysponowanie przez Użytkownika urząd" +
"zeniem teleinformatycznym z dostępem do sieci Internet, poprawnie skonfigurowaną" +
" przeglądarką internetową w wersji aktualnej bądź poprzedniej: Google Chrome, Mi" +
"crosoft Internet Explorer, Mozilla Firefox lub Opera, a także aktywnym i poprawn" +
"ie skonfigurowanym kontem poczty elektronicznej.\r\n7.\tKorzystanie z Serwisu nastę" +
"puje poprzez zapoznanie się z jego zawartością. \r\n8.\tZakończenie korzystania z S" +
"erwisu następuje poprzez jego opuszczenie.\r\n \r\n<strong>§2 Rejestracja i Logowani" +
"e</strong>\r\n1.\tZarządzanie Usługami odbywa się przy użyciu Konta Użytkownika. \r\n" +
"2.\tKorzystanie z Konta Użytkownika jest możliwe po Rejestracji i Logowaniu lub L" +
"ogowaniu przy użyciu zewnętrznego konta Klienta: Microsoft, Facebook lub Google." +
"\r\n3.\tRejestracja dokonywana jest poprzez wypełnienie i wysłanie Usługodawcy form" +
"ularza rejestracyjnego, który jest udostępniony w obszarze strony internetowej S" +
"erwisu.\r\n4.\tWypełnienie formularza dokonywane jest poprzez wypełnienie wszystkic" +
"h obowiązkowych oraz ewentualnie opcjonalnych pól formularza, przy użyciu prawdz" +
"iwych, kompletnych i dotyczących Użytkownika danych, a w szczególności Danych Ko" +
"ntaktowych Użytkownika.\r\n5.\tWysłanie formularza rejestracyjnego dokonywane jest " +
"poprzez jego wysłanie do Usługodawcy za pośrednictwem Serwisu, przy użyciu właśc" +
"iwej funkcjonalności, znajdującej się w obszarze formularza rejestracyjnego.\r\n6." +
"\tDokonując Logowania z pominięciem Rejestracji lub dokonując Rejestracji, Użytko" +
"wnik przyjmuje ofertę Usługodawcy w przedmiocie świadczenia na jego rzecz Usługi" +
" prowadzenia Konta Klienta.\r\n\r\n<strong>§3 Ogólne informacje na temat funkcjonaln" +
"ości Serwisu</strong>\r\n1.\tKorzystanie z funkcjonalności Konta Klienta jest bezpł" +
"atne i możliwe po zalogowaniu do Konta Klienta.\r\n2.\tUzyskanie dostępu do funkcjo" +
"nalności następuje poprzez jej wybór w obszarze zakładek zamieszczonych w górnej" +
" belce Serwisu.\r\n3.\tKatalog funkcjonalności Konta Klienta obejmuje udostępnienie" +
" funkcjonalności tworzenia i edycji listy gości, wydatków, zadań oraz planowania" +
" układu sali weselnej, drogą elektroniczną za pośrednictwem Serwisu.\r\n4.\tUżytkow" +
"nik może w każdej chwili zakończyć korzystanie z funkcjonalności poprzez porzuce" +
"nie dokonywanej czynności w obszarze Serwisu lub jego opuszczenie.\r\n\r\n<strong>§4" +
" Lista gości</strong>\r\n1.\tFunkcjonalność tworzenia i edycji listy gości umożliwi" +
"a tworzenie i edycję oznaczonej indywidualną nazwą listy gości weselnych.\r\n2.\tDo" +
"danie nowej grupy gości następuje poprzez uzupełnienie formularza dodania grupy " +
"gości o jej nazwę.\r\n3.\tDodanie nowej osoby w charakterze gościa następuje poprze" +
"z: \r\n1.\tuzupełnienie formularza dodania nowej osoby poprzez wprowadzenie jej imi" +
"enia, nazwiska, telefonu kontaktowego, adresu e-mail i adresu,\r\n2.\twybór statusu" +
" wieku: osoba dorosła albo dziecko oraz\r\n3.\twybór statusu obecności: potwierdzon" +
"y albo niepotwierdzony.\r\n4.\tWprowadzając dane osobowe gości, Użytkownik oświadcz" +
"a iż ich przetwarzanie następuje wyłącznie w celach osobistych lub domowych.\r\n5." +
"\tW przypadku, gdy dane osobowe gości są wprowadzane przez Użytkownika w celach i" +
"nnych niż osobiste lub domowe, przed wprowadzeniem danych Użytkownik jest zobowi" +
"ązany skontaktować się z Usługodawcą, celem zawarcia pisemnej umowy o powierzeni" +
"e danych osobowych, zgodnie z przepisami ustawy o ochronie danych osobowych.\r\n6." +
"\tUżytkownik może edytować lub usunąć wybraną grupę lub osobę w dowolnej chwili, " +
"przy użyciu właściwego przycisku.\r\n\r\n<strong>§5 Lista wydatków</strong>\r\n1.\tFunk" +
"cjonalność tworzenia i edycji listy wydatków umożliwia tworzenie, edycję i ekspo" +
"rt listy wydatków weselnych.\r\n2.\tWprowadzenie kwoty dostępnego budżetu następuje" +
" poprzez uzupełnienie formularza edycji listy wydatków o kwotę budżetu.\r\n3.\tDoda" +
"nie wydatku następuje poprzez uzupełnienie formularza dodania wydatku o nazwę lu" +
"b opis, ilość i cenę jednostkową.\r\n4.\tFormularz dodania wydatku automatycznie ob" +
"licza cenę wydatku, uwzględniając iloczyn ilości i ceny jednostkowej wydatku.\r\n5" +
".\tFormularz listy wydatków automatycznie oblicza wartość pozostałego budżetu, uw" +
"zględniając różnicę kwoty całkowitej wydatków oraz kwoty budżetu.\r\n6.\tUżytkownik" +
" może edytować lub usunąć wybrany wydatek w dowolnej chwili, przy użyciu właściw" +
"ego przycisku.\r\n7.\tUżytkownik może eksportować listę wydatków w dowolnej chwili " +
"do pliku w formacie PDF poprzez użycie właściwego przycisku.\r\n\r\n<strong>§6 Lista" +
" zadań</strong>\r\n1.\tFunkcjonalność tworzenia i edycji listy zadań umożliwia twor" +
"zenie i edycję listy zadań weselnych.\r\n2.\tDodanie nowego zadania następuje poprz" +
"ez uzupełnienie formularza dodania zadania o jego nazwę.\r\n3.\tEdycja zadania nast" +
"ępuje poprzez wybór jego pola i umożliwia:\r\n1.\twprowadzenie opisu zadania, \r\n2.\t" +
"nadanie mu statusu realizacji: nowe, trwające albo zrealizowane, \r\n3.\twprowadzen" +
"ie daty przypomnienia o zadaniu,\r\n4.\tprzypisanie karty do zadania, zawierającej " +
"zależnie od wyboru adres e-mail, dane osoby kontaktowej, adres, nr telefonu lub " +
"link url. \r\n4.\tUżytkownik może edytować lub usunąć wybrane zadanie w dowolnej ch" +
"wili, przy użyciu właściwego przycisku.\r\n\r\n<strong>§7 Sala weselna</strong>\r\n1.\t" +
"Funkcjonalność planowania sali weselnej umożliwia tworzenie i edycję graficznego" +
" planu ustawienia sali weselnej oraz posadzenia gości.\r\n2.\tPlanowanie ustawienia" +
" sali weselnej dokonywane jest poprzez dodawanie, przemieszczanie oraz usuwanie " +
"wizualizacji stołów i innych elementów metodą „przeciągnij i upuść”. \r\n3.\tPlanow" +
"anie posadzenia gości dokonywane jest poprzez przypisywanie wizualizacji gości d" +
"o wybranych miejsc siedzących metodą „przeciągnij i upuść”.\r\n4.\tUżytkownik może " +
"przenieść lub usunąć wybraną wizualizację stołu, gościa lub innego elementu w do" +
"wolnej chwili, przy użyciu właściwego przycisku.\r\n\r\n<strong>§8 Reklamacje</stron" +
"g>\r\n1.\tReklamacje z tytułu Usług świadczonych przez Usługodawcę można składać dr" +
"ogą elektroniczną lub tradycyjną, przy użyciu Danych Kontaktowych Usługodawcy.\r\n" +
"2.\tZgłoszenie reklamacyjne powinno zawierać opis problemu oraz dane identyfikacy" +
"jne Użytkownika.\r\n3.\tUsługodawca rozpoznaje reklamacje w terminie 14 dni od daty" +
" zgłoszenia. W treści składanej reklamacji zaleca się podanie Danych Kontaktowyc" +
"h Użytkownika, które posłużą udzieleniu odpowiedzi na reklamację oraz prowadzeni" +
"u korespondencji z nią związanej.\r\n4.\tReklamacje można składać z tytułu rękojmi " +
"za wady Usług. \r\n5.\tUsługodawca poinformuje Użytkownika o decyzji w przedmiocie " +
"rozpoznania reklamacji drogą elektroniczną lub pisemną, przy użyciu Danych Konta" +
"ktowych Użytkownika.\r\n6.\tKonsument posiada możliwość skorzystania z następującyc" +
"h pozasądowych sposobów rozpatrywania reklamacji i dochodzenia roszczeń:\r\n1.\tzło" +
"żenie wniosku o rozstrzygnięcie sporu wynikłego z zawartej umowy do stałego polu" +
"bownego sądu konsumenckiego działającego przy Inspekcji Handlowej,\r\n2.\tzłożenie " +
"wniosku o wszczęcie postępowania mediacyjnego w sprawie polubownego zakończenia " +
"sporu między Konsumentem, a Usługodawcą do Wojewódzkiego Inspektora Inspekcji Ha" +
"ndlowej,\r\n3.\tskorzystanie z pomocy powiatowego lub miejskiego rzecznika konsumen" +
"tów lub organizacji społecznej, do której zadań statutowych należy ochrona konsu" +
"mentów.\r\n\r\n<strong>§9 Odstąpienie od umowy</strong>\r\n1.\tKonsument może bez podaw" +
"ania przyczyny odstąpić w terminie 14 dni od Umowy o świadczenie Usługi, bez pod" +
"ania jakiejkolwiek przyczyny.\r\n2.\tTermin 14 dni na odstąpienie od umowy liczony " +
"jest od daty złożenia przez Konsumenta zamówienia na świadczenie Usługi przez Us" +
"ługodawcę.\r\n3.\tOświadczenie o odstąpieniu od umowy można złożyć na formularzu, k" +
"tórego wzór stanowi załącznik do Regulaminu zamieszczony w obszarze strony inter" +
"netowej Serwisu i dostępny <a");

WriteLiteral(" href=\"/Documents/GetWithdrawal\"");

WriteLiteral(">do pobrania tutaj</a>, ale nie jest to obowiązkowe.\r\n4.\tAby zachować termin do o" +
"dstąpienia od umowy, wystarczy, aby Konsument wysłał informację dotyczącą wykona" +
"nia przysługującego prawa odstąpienia przed upływem terminu wskazanego w pkt 2.\r" +
"\n5.\tAby skorzystać z prawa odstąpienia od umowy, Konsument musi poinformować Usł" +
"ugodawcę przy użyciu Danych Kontaktowych Usługodawcy, o swojej decyzji o odstąpi" +
"eniu od umowy w drodze jednoznacznego oświadczenia, na przykład pisma wysłanego " +
"pocztą tradycyjną lub elektroniczną.\r\n6.\tW przypadku otrzymania drogą elektronic" +
"zną oświadczenia o odstąpieniu przez Konsumenta od umowy, Usługodawca niezwłoczn" +
"ie prześle Użytkownikowi potwierdzenie jego otrzymania.\r\n7.\tW przypadku odstąpie" +
"nia od umowy, uważa się ją za niezawartą. Jeżeli Konsument złożył oświadczenie o" +
" odstąpieniu od umowy zanim Usługodawca przyjął jego ofertę, oferta przestaje wi" +
"ązać.\r\n\r\n<strong>§10 Postanowienia uzupełniające</strong>\r\n1.\tWszelkie znaki tow" +
"arowe, elementy graficzne i zdjęcia zamieszczone na stronie internetowej Serwisu" +
" są przedmiotem praw autorskich Usługodawcy lub ich właścicieli.\r\n2.\tDomena inte" +
"rnetowa Serwisu, jego logotypy, nazwa i Regulamin stanowią własność prawa autors" +
"kiego i przedmiot ochrony prawnej.\r\n3.\tUżytkownik przyjmuje do wiadomości, iż za" +
"bronione jest dostarczanie przez Użytkownika treści bezprawnych. \r\n4.\tUsługodawc" +
"a zobowiązuje się do dokładania należytych starań celem umożliwienia prawidłoweg" +
"o funkcjonowania Serwisu oraz do udzielania pomocy w rozwiązywaniu problemów tec" +
"hnicznych, związanych z jego działaniem.\r\n5.\tUsługodawca zobowiązuje się do prow" +
"adzania działań zmierzających do ochrony danych znajdujących się w Koncie Użytko" +
"wnika przed nieuprawnionym dostępem i użyciem. Użytkownik ponosi odpowiedzialnoś" +
"ć za następstwa ujawnienia swojego loginu lub hasła osobom trzecim.\r\n6.\tUsługoda" +
"wca nie ponosi odpowiedzialności za: \r\n1.\tprzerwy w prawidłowym funkcjonowaniu S" +
"erwisu oraz nienależyte wykonywanie Usług, spowodowane siłą wyższą, w stosunku d" +
"o Użytkowników niebędących Konsumentami,\r\n2.\tprzerwy w prawidłowym funkcjonowani" +
"u Serwisu oraz nienależyte wykonywanie Usług na rzecz Użytkowników niebędących K" +
"onsumentami, spowodowane czynnościami technicznymi lub przyczyną leżącą po stron" +
"ie podmiotów za pomocą których Serwis świadczy Usługi,\r\n3.\tkorzyści utracone prz" +
"ez Użytkownika niebędącego Konsumentem,\r\n4.\tnastępstwa wykorzystania danych dost" +
"ępowych do Konta Użytkownika przez osoby trzecie, w przypadku gdy weszły one w i" +
"ch posiadanie w następstwie naruszenia postanowień Regulaminu przez Użytkownika," +
"\r\n5.\tszkody spowodowane naruszeniem przez Użytkownika postanowień Regulaminu.\r\n\r" +
"\n<strong>§11 Postanowienia końcowe</strong>\r\n1.\tUsługodawca może zbierać informa" +
"cje, celem przechowywania ich lokalnie na urządzeniu Użytkownika, korzystając z " +
"mechanizmu pamięci przeglądarki przy użyciu plików „cookies”. \r\n2.\tDane osobowe " +
"użytkowników Serwisu przetwarzane są na podstawie zgody osób, których dotyczą lu" +
"b gdy jest to konieczne do realizacji umowy, gdy osoba której dane dotyczą jest " +
"jej stroną lub gdy jest to niezbędne do podjęcia działań przed zawarciem umowy n" +
"a żądanie osoby, której dane dotyczą.\r\n3.\tDane osobowe Użytkowników są zbierane " +
"w celu świadczenia Usług przez Usługodawcę. Osobom, których dane zostały przez U" +
"sługodawcę zebrane, przysługuje prawo dostępu do treści swoich danych, poprawian" +
"ia ich oraz wniesienia pisemnego umotywowanego żądania zaprzestania ich przetwar" +
"zania, a także sprzeciwu wobec tego.\r\n4.\tZasady przetwarzania danych osobowych, " +
"polityki prywatności oraz polityki plików „cookies” uregulowane zostały w dokume" +
"ncie „Polityka prywatności oraz polityka plików cookies”, stanowiącym załącznik " +
"do Regulaminu, zamieszczony w obszarze strony internetowej Serwisu i dostępny <a" +
"");

WriteLiteral(" href=\"/Documents/GetPrivacyAndCookiesPolicy\"");

WriteLiteral(@">do pobrania tutaj</a>.
5.	Zawierając umowę o świadczenie Usługi, Użytkownik dobrowolnie upoważnia Usługodawcę do przesyłania pod Dane Kontaktowe Użytkownika informacji związanych z Usługami oraz ich wykonaniem, a także informacji handlowych w przypadku wyrażenia na to odrębnej zgody.
6.	Użytkownik niebędący Konsumentem jest zobowiązany do informowania Usługodawcy o zmianach Danych Kontaktowych Użytkownika, pod rygorem skuteczności ich zastosowania przy doręczeniach.
7.	Postanowienia Regulaminu nie mają na celu wyłączać ani ograniczać praw Użytkownika będącego Konsumentem, wynikających z przepisów polskiego prawa powszechnie obowiązującego.
8.	W przypadku niezgodności postanowień Regulaminu z przepisami polskiego prawa powszechnie obowiązującego, stosuje się te przepisy. 
9.	W kwestiach nieuregulowanych Regulaminem zastosowanie mają przepisy polskiego prawa powszechnie obowiązującego.
</pre>
    </div>
</div>");

        }
    }
}
#pragma warning restore 1591
