#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Guests/EditorTemplates/PersonModel.cshtml")]
    public partial class _Views_Guests_EditorTemplates_PersonModel_cshtml_ : System.Web.Mvc.WebViewPage<AIT.WebUIComponent.Models.Guests.PersonModel>
    {
        public _Views_Guests_EditorTemplates_PersonModel_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"modal-slice hidden\"");

WriteAttribute("id", Tuple.Create(" id=\"", 86), Tuple.Create("\"", 121)
            
            #line 3 "..\..\Views\Guests\EditorTemplates\PersonModel.cshtml"
, Tuple.Create(Tuple.Create("", 91), Tuple.Create<System.Object, System.Int32>(ViewData["Index"]
            
            #line default
            #line hidden
, 91), false)
, Tuple.Create(Tuple.Create("", 109), Tuple.Create("-modal-slice", 109), true)
);

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 5 "..\..\Views\Guests\EditorTemplates\PersonModel.cshtml"
   Write(Html.TextBoxFor(model => model.Name, new { id = @ViewData["Index"] + "-nameTextBox", @class = "form-ctrl", placeholder = "Imię" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 8 "..\..\Views\Guests\EditorTemplates\PersonModel.cshtml"
   Write(Html.TextBoxFor(model => model.Surname, new { id = @ViewData["Index"] + "-surnameTextBox", @class = "form-ctrl", placeholder = "Nazwisko" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 11 "..\..\Views\Guests\EditorTemplates\PersonModel.cshtml"
   Write(Html.TextBoxFor(model => model.Phone, new { id = @ViewData["Index"] + "-phoneTextBox", @class = "form-ctrl", placeholder = "Telefon kontaktowy" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 14 "..\..\Views\Guests\EditorTemplates\PersonModel.cshtml"
   Write(Html.TextBoxFor(model => model.Email, new { id = @ViewData["Index"] + "-emailTextBox", @class = "form-ctrl", placeholder = "E-mail" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 17 "..\..\Views\Guests\EditorTemplates\PersonModel.cshtml"
   Write(Html.TextBoxFor(model => model.Address, new { id = @ViewData["Index"] + "-addressTextBox", @class = "form-ctrl", placeholder = "Adres" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 20 "..\..\Views\Guests\EditorTemplates\PersonModel.cshtml"
   Write(Html.DropDownListFor(model => model.Genre, new SelectList(Model.GenreCollection, "Value", "Text", Model.Genre), new { id = @ViewData["Index"] + "-genreList", @class = "form-ctrl" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-ctrl-desc\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 23 "..\..\Views\Guests\EditorTemplates\PersonModel.cshtml"
   Write(Html.LabelFor(model => model.Status));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">        \r\n");

WriteLiteral("        ");

            
            #line 26 "..\..\Views\Guests\EditorTemplates\PersonModel.cshtml"
   Write(Html.DropDownListFor(model => model.Status, new SelectList(Model.StatusCollection, "Value", "Text", Model.Status), new { id = @ViewData["Index"] + "-statusList", @class = "form-ctrl" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

WriteLiteral("    ");

            
            #line 28 "..\..\Views\Guests\EditorTemplates\PersonModel.cshtml"
Write(Html.Hidden("Id", Model.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 29 "..\..\Views\Guests\EditorTemplates\PersonModel.cshtml"
Write(Html.Hidden("GroupId", Model.GroupId));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>");

        }
    }
}
#pragma warning restore 1591
