#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Expenses/_CreateExpense.cshtml")]
    public partial class _Views_Expenses__CreateExpense_cshtml : System.Web.Mvc.WebViewPage<IList<AIT.WebUIComponent.Models.Expenses.ExpenseItemModel>>
    {
        public _Views_Expenses__CreateExpense_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Expenses\_CreateExpense.cshtml"
  
    var id = Model[0].Id;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"modal-slice\"");

WriteAttribute("id", Tuple.Create(" id=\"", 129), Tuple.Create("\"", 149)
            
            #line 7 "..\..\Views\Expenses\_CreateExpense.cshtml"
, Tuple.Create(Tuple.Create("", 134), Tuple.Create<System.Object, System.Int32>(id
            
            #line default
            #line hidden
, 134), false)
, Tuple.Create(Tuple.Create("", 137), Tuple.Create("-modal-slice", 137), true)
);

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form-ctrl-desc\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 9 "..\..\Views\Expenses\_CreateExpense.cshtml"
   Write(Html.LabelFor(model => model[0].Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 12 "..\..\Views\Expenses\_CreateExpense.cshtml"
   Write(Html.TextBoxFor(model => model[0].Description, new { id = id + "-Description", @class = "form-ctrl" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-ctrl-desc\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 15 "..\..\Views\Expenses\_CreateExpense.cshtml"
   Write(Html.LabelFor(model => model[0].Quantity));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 18 "..\..\Views\Expenses\_CreateExpense.cshtml"
   Write(Html.TextBoxFor(model => model[0].Quantity, new { id = id + "-Quantity", @class = "form-ctrl int-input calcField-" + id }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-ctrl-desc\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 21 "..\..\Views\Expenses\_CreateExpense.cshtml"
   Write(Html.LabelFor(model => model[0].UnitPrice));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 24 "..\..\Views\Expenses\_CreateExpense.cshtml"
   Write(Html.TextBoxFor(model => model[0].UnitPrice, new { id = id + "-UnitPrice", @class = "form-ctrl float-input calcField-" + id }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-ctrl-desc\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 27 "..\..\Views\Expenses\_CreateExpense.cshtml"
   Write(Html.LabelFor(model => model[0].Price));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 30 "..\..\Views\Expenses\_CreateExpense.cshtml"
   Write(Html.TextBoxFor(model => model[0].Price, new { id = id + "-Price", @class = "form-ctrl float-input" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(function () {\r\n            expensesManager.manageEditFields(");

            
            #line 35 "..\..\Views\Expenses\_CreateExpense.cshtml"
                                        Write(id);

            
            #line default
            #line hidden
WriteLiteral(");\r\n        });\r\n    </script>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
