#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Expenses/_EditExpense.cshtml")]
    public partial class _Views_Expenses__EditExpense_cshtml : System.Web.Mvc.WebViewPage<AIT.WebUIComponent.Models.Expenses.ExpenseItemModel>
    {
        public _Views_Expenses__EditExpense_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Expenses\_EditExpense.cshtml"
  
    var id = Model.Id;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row hidden-xs edit-expense\"");

WriteLiteral(">\r\n");

            
            #line 8 "..\..\Views\Expenses\_EditExpense.cshtml"
    
            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Expenses\_EditExpense.cshtml"
     using (Ajax.BeginForm("UpdateExpense", "Expenses", new AjaxOptions
    {
        OnBegin = "expensesManager.beforeExpenseUpdate(" + @id + ")",
        OnSuccess = "expensesManager.onExpenseUpdateSuccess",
        OnFailure = "expensesManager.onExpenseUpdateFailure(xhr, " + @id + ")",
        OnComplete = "expensesManager.onExpenseUpdateCompleted(" + @id + ")"
    }, new { id = "editExpenseForm-" + id }))
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"expense-update-area\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 18 "..\..\Views\Expenses\_EditExpense.cshtml"
           Write(Html.TextBoxFor(n => n.Description, new { id = id + "-Desc", @class = "expense-input" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"expense-update-area\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 23 "..\..\Views\Expenses\_EditExpense.cshtml"
           Write(Html.TextBoxFor(n => n.Quantity, new { id = id + "-Quantity", @class = "expense-input int-input calcField-" + id }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"col-sm-2\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"expense-update-area\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 28 "..\..\Views\Expenses\_EditExpense.cshtml"
           Write(Html.TextBoxFor(n => n.UnitPrice, new { id = id + "-UnitPrice", @class = "expense-input float-input calcField-" + id }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"col-sm-3\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"expense-update-area price\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 33 "..\..\Views\Expenses\_EditExpense.cshtml"
           Write(Html.TextBoxFor(n => n.Price, new { id = id + "-Price", @class = "expense-input float-input" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"expense-update-actions\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn-rounded btn-turquoise disabled\"");

WriteLiteral(" title=\"Zapisz\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"icon icon-lg icon-save\"");

WriteLiteral("></span>\r\n                </button>\r\n                <button");

WriteAttribute("id", Tuple.Create(" id=\"", 1771), Tuple.Create("\"", 1793)
, Tuple.Create(Tuple.Create("", 1776), Tuple.Create("btnCancelEdit-", 1776), true)
            
            #line 39 "..\..\Views\Expenses\_EditExpense.cshtml"
, Tuple.Create(Tuple.Create("", 1790), Tuple.Create<System.Object, System.Int32>(id
            
            #line default
            #line hidden
, 1790), false)
);

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn-rounded btn-dismiss\"");

WriteLiteral(" title=\"Anuluj\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"icon icon-lg icon-cancel\"");

WriteLiteral("></span>\r\n                </button>\r\n            </div>     \r\n        </div>\r\n");

            
            #line 44 "..\..\Views\Expenses\_EditExpense.cshtml"
        
            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\Expenses\_EditExpense.cshtml"
   Write(Html.Hidden("Id", id));

            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\Expenses\_EditExpense.cshtml"
                              
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(function () {\r\n            expensesManager.manageEditFields(");

            
            #line 49 "..\..\Views\Expenses\_EditExpense.cshtml"
                                        Write(id);

            
            #line default
            #line hidden
WriteLiteral(");\r\n        });\r\n    </script>\r\n</div>\r\n    \r\n");

        }
    }
}
#pragma warning restore 1591
