#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Expenses/_Expenses.cshtml")]
    public partial class _Views_Expenses__Expenses_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<AIT.WebUIComponent.Models.Expenses.ExpenseItemModel>>
    {
        public _Views_Expenses__Expenses_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <ul");

WriteLiteral(" id=\"expensesList\"");

WriteLiteral(" class=\"list-group\"");

WriteLiteral(">\r\n");

            
            #line 5 "..\..\Views\Expenses\_Expenses.cshtml"
        
            
            #line default
            #line hidden
            
            #line 5 "..\..\Views\Expenses\_Expenses.cshtml"
         foreach (var expense in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("            <li");

WriteLiteral(" class=\"list-group-item\"");

WriteAttribute("eid", Tuple.Create(" eid=\"", 232), Tuple.Create("\"", 249)
            
            #line 7 "..\..\Views\Expenses\_Expenses.cshtml"
, Tuple.Create(Tuple.Create("", 238), Tuple.Create<System.Object, System.Int32>(expense.Id
            
            #line default
            #line hidden
, 238), false)
);

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"list-item-content\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"expenses-content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row list-item-row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-xs-10 col-sm-6\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"list-item-checkbox\"");

WriteLiteral(" title=\"Zaznacz wydatek\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"btn-rounded btn-turquoise nohover btn-checkbox\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"icon icon-lg icon-coins\"");

WriteLiteral("></span>\r\n                                    </label>\r\n                         " +
"       </span>\r\n                                <span");

WriteLiteral(" class=\"checkbox-desc list-value\"");

WriteLiteral(" data-bind=\"description\"");

WriteLiteral(" data-bind-callback=\"expensesManager.updateFilterMap\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 19 "..\..\Views\Expenses\_Expenses.cshtml"
                               Write(expense.Description);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </span>\r\n                            </div>\r\n  " +
"                          <div");

WriteLiteral(" class=\"hidden-xs col-sm-1\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"list-value\"");

WriteLiteral(" data-bind=\"quantity\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 24 "..\..\Views\Expenses\_Expenses.cshtml"
                               Write(expense.Quantity);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </span>\r\n                            </div>\r\n  " +
"                          <div");

WriteLiteral(" class=\"hidden-xs col-sm-2\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"list-value\"");

WriteLiteral(" data-bind=\"unitPrice\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 29 "..\..\Views\Expenses\_Expenses.cshtml"
                               Write(expense.UnitPrice);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </span>\r\n                            </div>\r\n  " +
"                          <div");

WriteLiteral(" class=\"col-xs-2 col-sm-3\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"list-value\"");

WriteLiteral(" data-bind=\"price\"");

WriteLiteral(" data-bind-callback=\"expensesManager.updateExpensesMap\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 35 "..\..\Views\Expenses\_Expenses.cshtml"
                                   Write(expense.Price);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </span>\r\n                                </" +
"div>\r\n                                <div");

WriteAttribute("id", Tuple.Create(" id=\"", 2169), Tuple.Create("\"", 2200)
, Tuple.Create(Tuple.Create("", 2174), Tuple.Create("expenseBtnArea-", 2174), true)
            
            #line 38 "..\..\Views\Expenses\_Expenses.cshtml"
, Tuple.Create(Tuple.Create("", 2189), Tuple.Create<System.Object, System.Int32>(expense.Id
            
            #line default
            #line hidden
, 2189), false)
);

WriteLiteral(" class=\"hidden-xs pull-right\"");

WriteLiteral(" title=\"Edytuj wydatek\"");

WriteLiteral(">\r\n                                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn-rounded btn-turquoise btn-edit-expense\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"icon icon-lg icon-edit\"");

WriteLiteral("></span>\r\n                                    </button>\r\n                        " +
"            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn-rounded btn-dismiss btn-remove-expense\"");

WriteLiteral(" title=\"Usuń wydatek\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"icon icon-lg icon-trash\"");

WriteLiteral("></span>\r\n                                    </button>\r\n                        " +
"        </div>\r\n                            </div>                           \r\n " +
"                       </div>\r\n                    </div>\r\n                    <" +
"div");

WriteLiteral(" class=\"list-item-handle\"");

WriteLiteral(" title=\"Przeciągnij wydatek\"");

WriteLiteral("></div>\r\n                </div>\r\n            </li>\r\n");

            
            #line 52 "..\..\Views\Expenses\_Expenses.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </ul>\r\n</div> ");

        }
    }
}
#pragma warning restore 1591
