#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Expenses/_ExpensesInfo.cshtml")]
    public partial class _Views_Expenses__ExpensesInfo_cshtml : System.Web.Mvc.WebViewPage<AIT.WebUIComponent.Models.Expenses.ExpensesInfoModel>
    {
        public _Views_Expenses__ExpensesInfo_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"col-xs-12 col-sm-4\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"budget-text grey center\"");

WriteLiteral(">Budżet: </div>\r\n    <div");

WriteLiteral(" class=\"budget-area\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"displayBudgetArea\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"budget-value\"");

WriteLiteral(" data-bind=\"budgetValue\"");

WriteLiteral(">\r\n                ");

WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 9 "..\..\Views\Expenses\_ExpensesInfo.cshtml"
           Write(Model.Budget.Value);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"budget-edit\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btnEditBudget\"");

WriteLiteral(" class=\"btn-rounded btn-turquoise\"");

WriteLiteral(" title=\"Edytuj budżet\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"icon icon-lg icon-edit\"");

WriteLiteral("></span>\r\n                </button>\r\n            </div>\r\n        </div>\r\n        " +
"<div");

WriteLiteral(" id=\"updateBudgetArea\"");

WriteLiteral(" class=\"budget-update\"");

WriteLiteral(">\r\n");

            
            #line 18 "..\..\Views\Expenses\_ExpensesInfo.cshtml"
            
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Expenses\_ExpensesInfo.cshtml"
               Html.RenderPartial("_UpdateBudget", Model.Budget); 
            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"col-xs-12 col-sm-4\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"budget-calc\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"budget-text grey\"");

WriteLiteral(">Całkowite wydatki:</div>\r\n        <div");

WriteLiteral(" class=\"budget-text pink value\"");

WriteLiteral(" data-bind=\"totalPrice\"");

WriteLiteral(">");

            
            #line 25 "..\..\Views\Expenses\_ExpensesInfo.cshtml"
                                                              Write(Model.TotalPrice);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"col-xs-12 col-sm-4\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"budget-calc\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"budget-text grey\"");

WriteLiteral(">Pozostały budżet:</div>\r\n        <div");

WriteLiteral(" class=\"budget-text blue value\"");

WriteLiteral(" data-bind=\"budgetLeft\"");

WriteLiteral(">");

            
            #line 31 "..\..\Views\Expenses\_ExpensesInfo.cshtml"
                                                              Write(Model.BudgetLeft);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
