#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Expenses/_UpdateBudget.cshtml")]
    public partial class _Views_Expenses__UpdateBudget_cshtml : System.Web.Mvc.WebViewPage<AIT.WebUIComponent.Models.Expenses.BudgetModel>
    {
        public _Views_Expenses__UpdateBudget_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Expenses\_UpdateBudget.cshtml"
 using (Ajax.BeginForm("UpdateBudget", "Expenses", new AjaxOptions
{
    OnBegin = "budgetInfoManager.beforeUpdate",
    OnSuccess = "budgetInfoManager.onUpdateSuccess",
    OnFailure = "budgetInfoManager.onUpdateFailure"
}, new { id="updateBudgetForm" }))
{

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n");

WriteLiteral("        ");

            
            #line 11 "..\..\Views\Expenses\_UpdateBudget.cshtml"
   Write(Html.TextBoxFor(x => x.Value, new { @class = "expense-input edit-budget-input", id = "txtBudgetValue", value = Model.Value }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        \r\n        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" id=\"btnUpdateBudget\"");

WriteLiteral(" class=\"btn-rounded btn-turquoise disabled\"");

WriteLiteral(" title=\"Zapisz\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"icon icon-lg icon-save\"");

WriteLiteral("></span>\r\n        </button>\r\n        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btnCancelBudget\"");

WriteLiteral(" class=\"btn-rounded btn-dismiss\"");

WriteLiteral(" title=\"Anuluj\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"icon icon-lg icon-cancel\"");

WriteLiteral("></span>\r\n        </button>\r\n    </div>\r\n");

            
            #line 20 "..\..\Views\Expenses\_UpdateBudget.cshtml"
    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Expenses\_UpdateBudget.cshtml"
Write(Html.HiddenFor(x => x.Id));

            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Expenses\_UpdateBudget.cshtml"
                              
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
