#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Expenses/Index.cshtml")]
    public partial class _Views_Expenses_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Expenses_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Expenses\Index.cshtml"
  
    ViewBag.Title = " - wydatki";
    Layout = "~/Views/Shared/_LayoutSubPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" id=\"expensesContainer\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 8 "..\..\Views\Expenses\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Expenses\Index.cshtml"
           Html.RenderPartial("_Search"); 
            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"expensesInfo\"");

WriteLiteral(">\r\n            ");

WriteLiteral("\r\n        </div>\r\n        <hr");

WriteLiteral(" class=\"separator\"");

WriteLiteral(" />\r\n\r\n        <div");

WriteLiteral(" class=\"expense-actions\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#createExpensesModal\"");

WriteLiteral(" class=\"btn-simple wide\"");

WriteLiteral(">\r\n                DODAJ WYDATKI\r\n            </button>\r\n\r\n");

WriteLiteral("            ");

            
            #line 21 "..\..\Views\Expenses\Index.cshtml"
       Write(Html.ActionLink("EKSPORTUJ WYDATKI", "ExpensesPdf", "Pdf", null, new { id = "btnExpensesExport", @class = "btn-simple wide", target = "_blank" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row expenses-area\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"relative-position\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"sticky-top-wrapper\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"expensesHeader\"");

WriteLiteral(" class=\"expenses-header\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-xs-10 col-sm-6 text-center\"");

WriteLiteral(">Nazwa/Opis</div>\r\n                    <div");

WriteLiteral(" class=\"hidden-xs col-sm-1\"");

WriteLiteral(">Ilość</div>\r\n                    <div");

WriteLiteral(" class=\"hidden-xs col-sm-2\"");

WriteLiteral(">Cena jedn.</div>\r\n                    <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">Wartość</div>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"relative-position\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"expenses\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" id=\"expensesPanel\"");

WriteLiteral(" class=\"stick-bottom-panel\"");

WriteLiteral(">                    \r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#editExpensesModal\"");

WriteLiteral(" class=\"btn-rounded btn-turquoise\"");

WriteLiteral(" title=\"Edytuj zaznaczone wydatki\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"icon icon-lg icon-edit\"");

WriteLiteral("></span>\r\n                    </button>\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btnSumupExpenses\"");

WriteLiteral(" class=\"btn-rounded btn-turquoise\"");

WriteLiteral("\r\n                            data-toggle=\"popover\"");

WriteLiteral("\r\n                            data-placement=\"top\"");

WriteLiteral("\r\n                            data-container=\"#expensesPanel\"");

WriteLiteral("\r\n                            data-trigger=\"manual\"");

WriteLiteral("\r\n                            title=\"Podlicz zaznaczone wydatki\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"icon icon-lg icon-wallet\"");

WriteLiteral("></span>\r\n                    </button>\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btnExpensesToPdf\"");

WriteLiteral(" class=\"btn-rounded btn-turquoise\"");

WriteLiteral(" title=\"Eksportuj zaznaczone wydatki do pliku PDF\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"icon icon-lg icon-pdf\"");

WriteLiteral("></span>\r\n                    </button>\r\n                    <button");

WriteLiteral(" id=\"btnDeleteExpenses\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn-rounded btn-dismiss\"");

WriteLiteral(" title=\"Usuń zaznaczone wydatki\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"icon icon-lg icon-trash\"");

WriteLiteral("></span>\r\n                    </button>\r\n                    <button");

WriteLiteral(" id=\"btnClearSelected\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn-rounded btn-dismiss\"");

WriteLiteral(" title=\"Zamknij panel\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"icon icon-lg icon-hide\"");

WriteLiteral("></span>\r\n                    </button>\r\n                </div>\r\n            </di" +
"v>\r\n        </div>\r\n    </div>\r\n\r\n");

            
            #line 64 "..\..\Views\Expenses\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 64 "..\..\Views\Expenses\Index.cshtml"
      
        Html.RenderPartial("_ModalAnimate", new ViewDataDictionary { { "Action", "CreateExpenses" }, { "Controller", "Expenses" }, { "Id", "createExpensesModal" }, { "Desc", "DODAJ WYDATKI" } });
        Html.RenderPartial("_ModalAnimate", new ViewDataDictionary { { "Action", "UpdateExpenses" }, { "Controller", "Expenses" }, { "Id", "editExpensesModal" }, { "Desc", "EDYTUJ WYDATKI" } });
    
            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div");

WriteLiteral(" id=\"undoArea\"");

WriteLiteral(">\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 73 "..\..\Views\Expenses\Index.cshtml"
Write(Scripts.Render("~/bundles/expenses"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
