#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tasks/_Task.cshtml")]
    public partial class _Views_Tasks__Task_cshtml : System.Web.Mvc.WebViewPage<AIT.WebUIComponent.Models.Tasks.TaskModel>
    {
        public _Views_Tasks__Task_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Tasks\_Task.cshtml"
   var cards = Html.Raw(Json.Encode(Model.Cards)); 
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div>\r\n        <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 8 "..\..\Views\Tasks\_Task.cshtml"
       Write(Html.TextBoxFor(m => m.Title, new { @class = "form-ctrl", placeholder = "Nazwa zadania" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">            \r\n");

WriteLiteral("            ");

            
            #line 11 "..\..\Views\Tasks\_Task.cshtml"
       Write(Html.TextAreaFor(model => model.Description, new { @class = "form-ctrl", rows = 5, placeholder = "Opis zadania" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 14 "..\..\Views\Tasks\_Task.cshtml"
       Write(Html.DropDownListFor(model => model.State, new SelectList(Model.TaskStateCollection, "Value", "Text"), new { @class = "form-ctrl" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"form-ctrl-area form-task-reminder\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 18 "..\..\Views\Tasks\_Task.cshtml"
       Write(Html.TextBoxFor(model => model.ReminderDate, new { id = "txtReminderDate", @class = "form-ctrl", @readonly = "readonly", placeholder = "Data przypomnienia" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn-rounded btn-small btn-turquoise\"");

WriteLiteral(" id=\"btnReminderDate\"");

WriteLiteral(" title=\"Ustaw przypomnienie\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"icon icon-sm icon-calendar\"");

WriteLiteral("></span>\r\n            </button>\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn-rounded btn-small btn-dismiss\"");

WriteLiteral(" id=\"btnClearReminderDate\"");

WriteLiteral(" title=\"Usuń przypomnienie\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"icon icon-sm icon-trash\"");

WriteLiteral("></span>\r\n            </button>\r\n        </div>        \r\n    </div>\r\n    <div>\r\n " +
"       <div");

WriteLiteral(" class=\"form-ctrl-desc\"");

WriteLiteral(">\r\n            Karty do zadania:\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" id=\"cardsArea\"");

WriteLiteral(" class=\"cards-area\"");

WriteLiteral(" data-fl-dynamic-area>\r\n        ");

WriteLiteral("\r\n    </div>\r\n    <div>\r\n        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn-rounded btn-small btn-turquoise\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-task-id=\"");

            
            #line 36 "..\..\Views\Tasks\_Task.cshtml"
                                                                                                       Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-target=\"#taskCardModal\"");

WriteLiteral(" title=\"Dodaj nową kartę\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"icon icon-sm icon-add\"");

WriteLiteral("></span>\r\n        </button>\r\n    </div>    \r\n");

WriteLiteral("    ");

            
            #line 40 "..\..\Views\Tasks\_Task.cshtml"
Write(Html.HiddenFor(model => model.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    $(function () {\r\n        cardManager.renderCards(");

            
            #line 45 "..\..\Views\Tasks\_Task.cshtml"
                           Write(cards);

            
            #line default
            #line hidden
WriteLiteral(");\r\n    })\r\n</script>");

        }
    }
}
#pragma warning restore 1591
