//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIT.WebUIComponent.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIT.WebUIComponent.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string AcceptedDesc {
            get {
                return ResourceManager.GetString("AcceptedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add next expense.
        /// </summary>
        public static string AddNextExpenseLink {
            get {
                return ResourceManager.GetString("AddNextExpenseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add next.
        /// </summary>
        public static string AddNextPersonLink {
            get {
                return ResourceManager.GetString("AddNextPersonLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string AddressLbl {
            get {
                return ResourceManager.GetString("AddressLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults.
        /// </summary>
        public static string AdultDesc {
            get {
                return ResourceManager.GetString("AdultDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create group.
        /// </summary>
        public static string BtnCreateGroupDesc {
            get {
                return ResourceManager.GetString("BtnCreateGroupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export guests.
        /// </summary>
        public static string BtnExportGroupDesc {
            get {
                return ResourceManager.GetString("BtnExportGroupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelUpdateExpensesLink {
            get {
                return ResourceManager.GetString("CancelUpdateExpensesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string ChildDesc {
            get {
                return ResourceManager.GetString("ChildDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add expense.
        /// </summary>
        public static string CreateExpenseLink {
            get {
                return ResourceManager.GetString("CreateExpenseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new group.
        /// </summary>
        public static string CreateGroupDesc {
            get {
                return ResourceManager.GetString("CreateGroupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create guest(s).
        /// </summary>
        public static string CreatePersonsDesc {
            get {
                return ResourceManager.GetString("CreatePersonsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        public static string DeclinedDesc {
            get {
                return ResourceManager.GetString("DeclinedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of expenses deleted.
        /// </summary>
        public static string DeleteExpensesCommandDesc {
            get {
                return ResourceManager.GetString("DeleteExpensesCommandDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteExpensesLink {
            get {
                return ResourceManager.GetString("DeleteExpensesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following group was deleted.
        /// </summary>
        public static string DeleteGroupCommandDesc {
            get {
                return ResourceManager.GetString("DeleteGroupCommandDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeletePersonLink {
            get {
                return ResourceManager.GetString("DeletePersonLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of guests deleted.
        /// </summary>
        public static string DeletePersonsCommandDesc {
            get {
                return ResourceManager.GetString("DeletePersonsCommandDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done task.
        /// </summary>
        public static string DoneTaskDesc {
            get {
                return ResourceManager.GetString("DoneTaskDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditExpensesLink {
            get {
                return ResourceManager.GetString("EditExpensesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditPersonLink {
            get {
                return ResourceManager.GetString("EditPersonLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailLbl {
            get {
                return ResourceManager.GetString("EmailLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error has occured. Please try again or contact us..
        /// </summary>
        public static string ErrorInfo {
            get {
                return ResourceManager.GetString("ErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        public static string GroupNamePlaceholder {
            get {
                return ResourceManager.GetString("GroupNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string MembersInfoAcceptedDesc {
            get {
                return ResourceManager.GetString("MembersInfoAcceptedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults.
        /// </summary>
        public static string MembersInfoAdultDesc {
            get {
                return ResourceManager.GetString("MembersInfoAdultDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string MembersInfoChildDesc {
            get {
                return ResourceManager.GetString("MembersInfoChildDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        public static string MembersInfoDeclinedDesc {
            get {
                return ResourceManager.GetString("MembersInfoDeclinedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconfirmed.
        /// </summary>
        public static string MembersInfoUnconfirmedDesc {
            get {
                return ResourceManager.GetString("MembersInfoUnconfirmedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameLbl {
            get {
                return ResourceManager.GetString("NameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task.
        /// </summary>
        public static string NewTaskDesc {
            get {
                return ResourceManager.GetString("NewTaskDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongoing task.
        /// </summary>
        public static string OngoingTaskDesc {
            get {
                return ResourceManager.GetString("OngoingTaskDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string PhoneLbl {
            get {
                return ResourceManager.GetString("PhoneLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table (rectangular).
        /// </summary>
        public static string RectTableDesc {
            get {
                return ResourceManager.GetString("RectTableDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table (round).
        /// </summary>
        public static string RoundTableDesc {
            get {
                return ResourceManager.GetString("RoundTableDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusLbl {
            get {
                return ResourceManager.GetString("StatusLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string SurnameLbl {
            get {
                return ResourceManager.GetString("SurnameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconfirmed.
        /// </summary>
        public static string UnconfirmedDesc {
            get {
                return ResourceManager.GetString("UnconfirmedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateExpensesLink {
            get {
                return ResourceManager.GetString("UpdateExpensesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update group name.
        /// </summary>
        public static string UpdateGroupDesc {
            get {
                return ResourceManager.GetString("UpdateGroupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update persons.
        /// </summary>
        public static string UpdatePersonsDesc {
            get {
                return ResourceManager.GetString("UpdatePersonsDesc", resourceCulture);
            }
        }
    }
}
