#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Services/Emails/Templates/ConfirmChangedEmail.cshtml")]
    public partial class _Services_Emails_Templates_ConfirmChangedEmail_cshtml : System.Web.Mvc.WebViewPage<AIT.WebUIComponent.Models.Emails.SystemMessage>
    {
        public _Services_Emails_Templates_ConfirmChangedEmail_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(" xmlns=\"http://www.w3.org/1999/xhtml\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n</head>\r\n<body>\r\n    <p>\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 207), Tuple.Create("\"", 233)
, Tuple.Create(Tuple.Create("", 213), Tuple.Create("cid:", 213), true)
            
            #line 11 "..\..\Services\Emails\Templates\ConfirmChangedEmail.cshtml"
, Tuple.Create(Tuple.Create("", 217), Tuple.Create<System.Object, System.Int32>(Model.ContentId
            
            #line default
            #line hidden
, 217), false)
);

WriteLiteral(" />\r\n    </p>\r\n    <p>\r\n        Witaj ");

            
            #line 14 "..\..\Services\Emails\Templates\ConfirmChangedEmail.cshtml"
         Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral(".\r\n    </p>\r\n    <p>\r\n        Adres e-mail w serwisie <a");

WriteLiteral(" href=\"https://zamilowani.pl\"");

WriteLiteral(">Zamiłowani.pl</a> został zmieniony.\r\n    </p>\r\n    <p>\r\n        Aktywuj swoje ko" +
"nto klikając w ten <a");

WriteAttribute("href", Tuple.Create(" href=\"", 470), Tuple.Create("\"", 495)
            
            #line 20 "..\..\Services\Emails\Templates\ConfirmChangedEmail.cshtml"
, Tuple.Create(Tuple.Create("", 477), Tuple.Create<System.Object, System.Int32>(Model.CallbackUrl
            
            #line default
            #line hidden
, 477), false)
);

WriteLiteral(">link</a>.\r\n    </p>\r\n    <p>\r\n        <span>Zespół </span><span>Zamiłowani</span" +
"><span>.pl</span>\r\n    </p>\r\n</body>\r\n</html>  ");

        }
    }
}
#pragma warning restore 1591
