#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Services/Emails/Templates/FeedbackEmail.cshtml")]
    public partial class _Services_Emails_Templates_FeedbackEmail_cshtml : System.Web.Mvc.WebViewPage<AIT.WebUIComponent.Models.Emails.UserMessage>
    {
        public _Services_Emails_Templates_FeedbackEmail_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(" xmlns=\"http://www.w3.org/1999/xhtml\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n        .pre-style {\r\n            white-space: pre-line;\r\n        }\r\n    </sty" +
"le>\r\n</head>\r\n<body>\r\n    <p>\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 317), Tuple.Create("\"", 343)
, Tuple.Create(Tuple.Create("", 323), Tuple.Create("cid:", 323), true)
            
            #line 16 "..\..\Services\Emails\Templates\FeedbackEmail.cshtml"
, Tuple.Create(Tuple.Create("", 327), Tuple.Create<System.Object, System.Int32>(Model.ContentId
            
            #line default
            #line hidden
, 327), false)
);

WriteLiteral(" />\r\n    </p>\r\n    <p>\r\n        Wiadomość od ");

            
            #line 19 "..\..\Services\Emails\Templates\FeedbackEmail.cshtml"
                Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral(".\r\n    </p>\r\n    <p>\r\n        Wprowadzony adres e-mail: ");

            
            #line 22 "..\..\Services\Emails\Templates\FeedbackEmail.cshtml"
                             Write(Model.Email);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n    <p>\r\n        Treść:\r\n    </p>\r\n    <pre");

WriteLiteral(" class=\"pre-style\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 28 "..\..\Services\Emails\Templates\FeedbackEmail.cshtml"
   Write(Model.Body);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </pre>\r\n</body>\r\n</html>  ");

        }
    }
}
#pragma warning restore 1591
