#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Guests/_CreatePerson.cshtml")]
    public partial class _Views_Guests__CreatePerson_cshtml : System.Web.Mvc.WebViewPage<IList<AIT.WebUIComponent.Models.Guests.PersonModel>>
    {
        public _Views_Guests__CreatePerson_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

            
            #line 6 "..\..\Views\Guests\_CreatePerson.cshtml"
  
    int id = Model[0].Id;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"modal-slice\"");

WriteAttribute("id", Tuple.Create(" id=\"", 383), Tuple.Create("\"", 403)
            
            #line 10 "..\..\Views\Guests\_CreatePerson.cshtml"
, Tuple.Create(Tuple.Create("", 388), Tuple.Create<System.Object, System.Int32>(id
            
            #line default
            #line hidden
, 388), false)
, Tuple.Create(Tuple.Create("", 391), Tuple.Create("-modal-slice", 391), true)
);

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 12 "..\..\Views\Guests\_CreatePerson.cshtml"
   Write(Html.TextBoxFor(model => model[0].Name, new { id = @id + "-nameTextBox", @class = "form-ctrl", placeholder = "Imię" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 15 "..\..\Views\Guests\_CreatePerson.cshtml"
   Write(Html.TextBoxFor(model => model[0].Surname, new { id = @id + "-surnameTextBox", @class = "form-ctrl", placeholder = "Nazwisko" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 18 "..\..\Views\Guests\_CreatePerson.cshtml"
   Write(Html.TextBoxFor(model => model[0].Phone, new { id = @id + "-phoneTextBox", @class = "form-ctrl", placeholder = "Telefon kontaktowy" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 21 "..\..\Views\Guests\_CreatePerson.cshtml"
   Write(Html.TextBoxFor(model => model[0].Email, new { id = @id + "-emailTextBox", @class = "form-ctrl", placeholder = "E-mail" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 24 "..\..\Views\Guests\_CreatePerson.cshtml"
   Write(Html.TextBoxFor(model => model[0].Address, new { id = @id + "-addressTextBox", @class = "form-ctrl", placeholder = "Adres" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">        \r\n");

WriteLiteral("        ");

            
            #line 27 "..\..\Views\Guests\_CreatePerson.cshtml"
   Write(Html.DropDownListFor(model => model[0].Genre, new SelectList(Model[0].GenreCollection, "Value", "Text"), new { id = @id + "-genreList", @class = "form-ctrl" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-ctrl-desc\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 30 "..\..\Views\Guests\_CreatePerson.cshtml"
   Write(Html.LabelFor(model => model[0].Status));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">        \r\n");

WriteLiteral("        ");

            
            #line 33 "..\..\Views\Guests\_CreatePerson.cshtml"
   Write(Html.DropDownListFor(model => model[0].Status, new SelectList(Model[0].StatusCollection, "Value", "Text"), new { id = @id + "-statusList", @class = "form-ctrl" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

WriteLiteral("    ");

            
            #line 35 "..\..\Views\Guests\_CreatePerson.cshtml"
Write(Html.HiddenFor(model => model[0].GroupId));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
