#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Guests/_CreateGroup.cshtml")]
    public partial class _Views_Guests__CreateGroup_cshtml : System.Web.Mvc.WebViewPage<AIT.WebUIComponent.Models.Guests.GroupModel>
    {
        public _Views_Guests__CreateGroup_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"createGroupModal\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"lblCreateGroup\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog modal-sm\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n");

            
            #line 6 "..\..\Views\Guests\_CreateGroup.cshtml"
            
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\Guests\_CreateGroup.cshtml"
             using (Ajax.BeginForm("AddGroup", "Guests", null, new AjaxOptions
            {
                OnBegin = "groupManager.beforeCreate",
                OnSuccess = "groupManager.onCreateSuccess",
                OnFailure = "groupManager.onCreateFailure"
            }, new { autocomplete = "off" }))
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn-rounded btn-small btn-dismiss right\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"icon icon-sm icon-cancel\"");

WriteLiteral("></span>\r\n                    </button>\r\n                    <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" id=\"lblCreateGroup\"");

WriteLiteral(">STWÓRZ NOWĄ GRUPĘ</h4>\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 21 "..\..\Views\Guests\_CreateGroup.cshtml"
                   Write(Html.TextBoxFor(n => n.Name, new { @class = "form-ctrl uppercase", placeholder = "Nazwa grupy", id = "txtGroupName" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn-rounded btn-turquoise disabled\"");

WriteLiteral(" title=\"Zapisz\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"icon icon-lg icon-save\"");

WriteLiteral("></span>\r\n                    </button>\r\n                </div>\r\n");

            
            #line 29 "..\..\Views\Guests\_CreateGroup.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
