#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Guests/_Group.cshtml")]
    public partial class _Views_Guests__Group_cshtml : System.Web.Mvc.WebViewPage<AIT.WebUIComponent.Models.Guests.GroupModel>
    {
        public _Views_Guests__Group_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"group-item\"");

WriteAttribute("gid", Tuple.Create(" gid=\"", 77), Tuple.Create("\"", 92)
            
            #line 3 "..\..\Views\Guests\_Group.cshtml"
, Tuple.Create(Tuple.Create("", 83), Tuple.Create<System.Object, System.Int32>(Model.Id
            
            #line default
            #line hidden
, 83), false)
);

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"relative-position\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"sticky-top-wrapper group-box-wrapper\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"group-box\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"group-box-item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"group-info\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"group-name truncate\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 10 "..\..\Views\Guests\_Group.cshtml"
                       Write(Model.Name.ToUpper());

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"info-area\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"members-count\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"visible-xs visible-sm pull-left\"");

WriteLiteral(">(</span>\r\n                                <span");

WriteLiteral(" class=\"visible-md visible-lg pull-left\"");

WriteLiteral(">Liczba gości: </span>\r\n                                <span");

WriteLiteral(" class=\"counter\"");

WriteAttribute("id", Tuple.Create(" id=\"", 812), Tuple.Create("\"", 839)
, Tuple.Create(Tuple.Create("", 817), Tuple.Create("membersCount-", 817), true)
            
            #line 16 "..\..\Views\Guests\_Group.cshtml"
, Tuple.Create(Tuple.Create("", 830), Tuple.Create<System.Object, System.Int32>(Model.Id
            
            #line default
            #line hidden
, 830), false)
);

WriteLiteral(">0</span>\r\n                                <span");

WriteLiteral(" class=\"visible-xs visible-sm pull-right\"");

WriteLiteral(">)</span>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"info-action\"");

WriteLiteral(">\r\n                                <button");

WriteAttribute("id", Tuple.Create(" id=\"", 1070), Tuple.Create("\"", 1099)
, Tuple.Create(Tuple.Create("", 1075), Tuple.Create("btnMembersInfo-", 1075), true)
            
            #line 20 "..\..\Views\Guests\_Group.cshtml"
, Tuple.Create(Tuple.Create("", 1090), Tuple.Create<System.Object, System.Int32>(Model.Id
            
            #line default
            #line hidden
, 1090), false)
);

WriteLiteral(" class=\"btn-rounded btn-small btn-turquoise nohover btn-members-info\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"icon icon-sm icon-expand\"");

WriteLiteral("></span>\r\n                                </button>\r\n                            " +
"</div>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"members-info-panel\"");

WriteAttribute("id", Tuple.Create(" id=\"", 1436), Tuple.Create("\"", 1467)
, Tuple.Create(Tuple.Create("", 1441), Tuple.Create("membersInfoPanel-", 1441), true)
            
            #line 25 "..\..\Views\Guests\_Group.cshtml"
, Tuple.Create(Tuple.Create("", 1458), Tuple.Create<System.Object, System.Int32>(Model.Id
            
            #line default
            #line hidden
, 1458), false)
);

WriteLiteral(">\r\n");

            
            #line 26 "..\..\Views\Guests\_Group.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Guests\_Group.cshtml"
                               Html.RenderPartial("_MembersInfo"); 
            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"group-actions\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn-rounded btn-dismiss btn-delete-group\"");

WriteLiteral(" title=\"Usuń grupę\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"icon icon-lg icon-trash\"");

WriteLiteral("></span>\r\n                        </button>\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#editGroupModal\"");

WriteLiteral(" class=\"btn-rounded btn-turquoise\"");

WriteLiteral("  title=\"Edytuj nazwę grupy\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"icon icon-lg icon-edit\"");

WriteLiteral("></span>\r\n                        </button>                        \r\n            " +
"            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#createPersonsModal\"");

WriteLiteral(" class=\"btn-rounded btn-turquoise\"");

WriteLiteral(" title=\"Dodaj osoby do grupy\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"icon icon-lg icon-add\"");

WriteLiteral("></span>\r\n                        </button>\r\n                    </div>\r\n        " +
"        </div>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"members\"");

WriteLiteral(">\r\n            <div>\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <ul");

WriteAttribute("id", Tuple.Create(" id=\"", 2638), Tuple.Create("\"", 2660)
, Tuple.Create(Tuple.Create("", 2643), Tuple.Create("members-", 2643), true)
            
            #line 46 "..\..\Views\Guests\_Group.cshtml"
, Tuple.Create(Tuple.Create("", 2651), Tuple.Create<System.Object, System.Int32>(Model.Id
            
            #line default
            #line hidden
, 2651), false)
);

WriteLiteral(" class=\"list-group group-members\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n                    </ul>\r\n                </div>\r\n            </div>\r\n\r\n      " +
"      <div");

WriteAttribute("id", Tuple.Create(" id=\"", 2896), Tuple.Create("\"", 2923)
, Tuple.Create(Tuple.Create("", 2901), Tuple.Create("membersPanel-", 2901), true)
            
            #line 52 "..\..\Views\Guests\_Group.cshtml"
, Tuple.Create(Tuple.Create("", 2914), Tuple.Create<System.Object, System.Int32>(Model.Id
            
            #line default
            #line hidden
, 2914), false)
);

WriteLiteral(" class=\"stick-bottom-panel\"");

WriteLiteral(" title=\"Zamknij panel\"");

WriteLiteral(">                \r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#editPersonsModal\"");

WriteLiteral(" class=\"btn-rounded btn-turquoise\"");

WriteLiteral(" title=\"Edytuj zaznaczone osoby\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"icon icon-lg icon-edit\"");

WriteLiteral("></span>\r\n                </button>\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn-rounded btn-dismiss btn-delete-members\"");

WriteLiteral(" title=\"Usuń zaznaczone osoby\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"icon icon-lg icon-trash\"");

WriteLiteral("></span>\r\n                </button>\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn-rounded btn-dismiss btn-clear-selected\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"icon icon-lg icon-hide\"");

WriteLiteral("></span>\r\n                </button>\r\n            </div>\r\n        </div>\r\n    </di" +
"v>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
