#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Guests/_MembersInfo.cshtml")]
    public partial class _Views_Guests__MembersInfo_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Guests__MembersInfo_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div>\r\n    <span>\r\n        Zaakceptowani:\r\n    </span>\r\n    <span");

WriteLiteral(" class=\"bolded\"");

WriteLiteral(" data-bind=\"accepted\"");

WriteLiteral(">0</span>\r\n</div>\r\n<div>\r\n    <span>\r\n        - Dorośli:\r\n    </span>\r\n    <span");

WriteLiteral(" class=\"bolded\"");

WriteLiteral(" data-bind=\"acceptedAdults\"");

WriteLiteral(">0</span>\r\n</div>\r\n<div>\r\n    <span>\r\n        - Dzieci:\r\n    </span>\r\n    <span");

WriteLiteral(" class=\"bolded\"");

WriteLiteral(" data-bind=\"acceptedChild\"");

WriteLiteral(">0</span>\r\n</div>\r\n<div>\r\n    <span>\r\n        Ubyło:\r\n    </span>\r\n    <span");

WriteLiteral(" class=\"bolded\"");

WriteLiteral(" data-bind=\"declined\"");

WriteLiteral(">0</span>\r\n</div>\r\n<div>\r\n    <span>\r\n        Niepotwierdzeni:\r\n    </span>\r\n    " +
"<span");

WriteLiteral(" class=\"bolded\"");

WriteLiteral(" data-bind=\"unconfirmed\"");

WriteLiteral(">0</span>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
