#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Guests/_Person.cshtml")]
    public partial class _Views_Guests__Person_cshtml : System.Web.Mvc.WebViewPage<AIT.WebUIComponent.Models.Guests.PersonModel>
    {
        public _Views_Guests__Person_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"row list-item-row\"");

WriteAttribute("pid", Tuple.Create(" pid=\"", 85), Tuple.Create("\"", 100)
            
            #line 3 "..\..\Views\Guests\_Person.cshtml"
, Tuple.Create(Tuple.Create("", 91), Tuple.Create<System.Object, System.Int32>(Model.Id
            
            #line default
            #line hidden
, 91), false)
);

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-xs-10 col-sm-6 col-md-9 col-lg-6\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"list-item-checkbox\"");

WriteLiteral(" title=\"Zaznacz osobę\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"btn-rounded btn-turquoise nohover btn-checkbox\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"icon icon-lg icon-person\"");

WriteLiteral("></span>\r\n            </label>\r\n        </span>\r\n        <span");

WriteLiteral(" class=\"checkbox-desc list-value\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 12 "..\..\Views\Guests\_Person.cshtml"
       Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 12 "..\..\Views\Guests\_Person.cshtml"
                   Write(Model.Surname);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"hidden-xs hidden-md col-sm-3\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"list-value\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 17 "..\..\Views\Guests\_Person.cshtml"
       Write(Model.Phone);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-xs-2 col-sm-3\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"hidden-xs person-action\"");

WriteLiteral(">\r\n                <div");

WriteAttribute("class", Tuple.Create(" class=\"", 843), Tuple.Create("\"", 883)
, Tuple.Create(Tuple.Create("", 851), Tuple.Create("person-status", 851), true)
            
            #line 23 "..\..\Views\Guests\_Person.cshtml"
, Tuple.Create(Tuple.Create(" ", 864), Tuple.Create<System.Object, System.Int32>(Model.StatusValue
            
            #line default
            #line hidden
, 865), false)
);

WriteLiteral(" title=\"Status osoby\"");

WriteLiteral("></div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"hidden-xs person-action\"");

WriteLiteral(">\r\n");

            
            #line 26 "..\..\Views\Guests\_Person.cshtml"
                
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Guests\_Person.cshtml"
                 if (Model.IsInnerGroupMember)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <button");

WriteLiteral(" class=\"btn-rounded btn-turquoise btn-unchain\"");

WriteLiteral(" title=\"Odłącz osobę\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"icon icon-lg icon-unchain\"");

WriteLiteral("></span>\r\n                    </button>\r\n");

            
            #line 31 "..\..\Views\Guests\_Person.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 1337), Tuple.Create("\"", 1405)
, Tuple.Create(Tuple.Create("", 1345), Tuple.Create("btn-rounded", 1345), true)
, Tuple.Create(Tuple.Create(" ", 1356), Tuple.Create("btn-turquoise", 1357), true)
, Tuple.Create(Tuple.Create(" ", 1370), Tuple.Create("btn-chain", 1371), true)
, Tuple.Create(Tuple.Create(" ", 1380), Tuple.Create("btn-chain-", 1381), true)
            
            #line 34 "..\..\Views\Guests\_Person.cshtml"
, Tuple.Create(Tuple.Create("", 1391), Tuple.Create<System.Object, System.Int32>(Model.GroupId
            
            #line default
            #line hidden
, 1391), false)
);

WriteLiteral(" title=\"Powiąż z inną osobą lub grupą osób\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"icon icon-lg icon-chain\"");

WriteLiteral("></span>\r\n                    </div>\r\n");

            
            #line 37 "..\..\Views\Guests\_Person.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n            <div");

WriteLiteral(" class=\"person-action\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn-rounded btn-turquoise nohover btn-person-details\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" title=\"Pokaż szczegóły\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"icon icon-lg icon-expand\"");

WriteLiteral("></span>\r\n                </button>\r\n            </div>\r\n        </div>\r\n    </di" +
"v>\r\n    <div");

WriteLiteral(" class=\"col-xs-12 person-item-details\"");

WriteAttribute("id", Tuple.Create(" id=\"", 1945), Tuple.Create("\"", 1974)
, Tuple.Create(Tuple.Create("", 1950), Tuple.Create("person-details-", 1950), true)
            
            #line 46 "..\..\Views\Guests\_Person.cshtml"
, Tuple.Create(Tuple.Create("", 1965), Tuple.Create<System.Object, System.Int32>(Model.Id
            
            #line default
            #line hidden
, 1965), false)
);

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n            <tr>\r\n                <td");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">");

            
            #line 49 "..\..\Views\Guests\_Person.cshtml"
                           Write(Html.DisplayFor(x => x.GenreText));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            </tr>\r\n            <tr>\r\n                <td");

WriteLiteral(" class=\"narrow-column\"");

WriteLiteral(">");

            
            #line 52 "..\..\Views\Guests\_Person.cshtml"
                                     Write(Html.LabelFor(x => x.Status));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 53 "..\..\Views\Guests\_Person.cshtml"
               Write(Html.DisplayFor(x => x.StatusText));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            </tr>\r\n");

            
            #line 55 "..\..\Views\Guests\_Person.cshtml"
            
            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\Guests\_Person.cshtml"
             if (Model.IsEmailDefined)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");

            
            #line 58 "..\..\Views\Guests\_Person.cshtml"
                   Write(Html.LabelFor(x => x.Email));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 59 "..\..\Views\Guests\_Person.cshtml"
                   Write(Html.DisplayFor(x => x.Email));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n");

            
            #line 61 "..\..\Views\Guests\_Person.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 62 "..\..\Views\Guests\_Person.cshtml"
             if (Model.IsAddressDefined)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");

            
            #line 65 "..\..\Views\Guests\_Person.cshtml"
                   Write(Html.LabelFor(x => x.Address));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 66 "..\..\Views\Guests\_Person.cshtml"
                   Write(Html.DisplayFor(x => x.Address));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n");

            
            #line 68 "..\..\Views\Guests\_Person.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 69 "..\..\Views\Guests\_Person.cshtml"
             if (Model.IsPhoneDefined)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr");

WriteLiteral(" class=\"visible-xs visible-md\"");

WriteLiteral(">\r\n                    <td>");

            
            #line 72 "..\..\Views\Guests\_Person.cshtml"
                   Write(Html.LabelFor(x => x.Phone));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 73 "..\..\Views\Guests\_Person.cshtml"
                   Write(Html.DisplayFor(x => x.Phone));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n");

            
            #line 75 "..\..\Views\Guests\_Person.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <tr");

WriteLiteral(" class=\"visible-xs\"");

WriteLiteral(">\r\n                <td");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"text-center inner-actions\"");

WriteLiteral(">\r\n");

            
            #line 79 "..\..\Views\Guests\_Person.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 79 "..\..\Views\Guests\_Person.cshtml"
                         if (Model.IsInnerGroupMember)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <button");

WriteLiteral(" class=\"btn-rounded btn-turquoise btn-unchain\"");

WriteLiteral(" title=\"Odłącz osobę\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"icon icon-lg icon-unchain\"");

WriteLiteral("></span>\r\n                            </button>\r\n");

            
            #line 84 "..\..\Views\Guests\_Person.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"inline-block\"");

WriteLiteral(">\r\n                                <div");

WriteAttribute("class", Tuple.Create(" class=\"", 3653), Tuple.Create("\"", 3721)
, Tuple.Create(Tuple.Create("", 3661), Tuple.Create("btn-rounded", 3661), true)
, Tuple.Create(Tuple.Create(" ", 3672), Tuple.Create("btn-turquoise", 3673), true)
, Tuple.Create(Tuple.Create(" ", 3686), Tuple.Create("btn-chain", 3687), true)
, Tuple.Create(Tuple.Create(" ", 3696), Tuple.Create("btn-chain-", 3697), true)
            
            #line 88 "..\..\Views\Guests\_Person.cshtml"
          , Tuple.Create(Tuple.Create("", 3707), Tuple.Create<System.Object, System.Int32>(Model.GroupId
            
            #line default
            #line hidden
, 3707), false)
);

WriteLiteral(" title=\"Powiąż z inną osobą lub grupą osób\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"icon icon-lg icon-chain\"");

WriteLiteral("></span>\r\n                                </div>\r\n                            </d" +
"iv>\r\n");

            
            #line 92 "..\..\Views\Guests\_Person.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </td>\r\n            </tr>\r\n        </t" +
"able>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
