#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Guests/_PersonsList.cshtml")]
    public partial class _Views_Guests__PersonsList_cshtml : System.Web.Mvc.WebViewPage<AIT.WebUIComponent.Models.Guests.MembersModel>
    {
        public _Views_Guests__PersonsList_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Guests\_PersonsList.cshtml"
 foreach (var person in Model.Members)
{
    if (Model.OpenTag(person))
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("<li class=\"list-group-item\">\r\n");

WriteLiteral("            ");

WriteLiteral("<div class=\"list-item-content\">\r\n");

WriteLiteral("                ");

WriteLiteral("<div class=\"members-content ");

            
            #line 9 "..\..\Views\Guests\_PersonsList.cshtml"
                                          Write(string.Format("{0}-{1}", person.IsInnerGroupMember ? "connect-to-inner-group" : "single-person", Model.UniqueId));

            
            #line default
            #line hidden
WriteLiteral("\" key=\"");

            
            #line 9 "..\..\Views\Guests\_PersonsList.cshtml"
                                                                                                                                                                   Write(person.InnerGroupKey);

            
            #line default
            #line hidden
WriteLiteral("\">                    \r\n");

            
            #line 10 "..\..\Views\Guests\_PersonsList.cshtml"
    }

                    Html.RenderPartial("_Person", person);

    if (Model.CloseTag(person))
    {                    

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("</div>        \r\n");

WriteLiteral("                ");

WriteLiteral("<div class=\"list-item-handle\" title=\"Przeciągnij osobę\"></div>            \r\n");

WriteLiteral("            ");

WriteLiteral("</div>\r\n");

WriteLiteral("        ");

WriteLiteral("</li>                    \r\n");

            
            #line 20 "..\..\Views\Guests\_PersonsList.cshtml"
    }
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
