#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Guests\Index.cshtml"
    using AIT.WebUIComponent.Models.Guests;
    
    #line default
    #line hidden
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Guests/Index.cshtml")]
    public partial class _Views_Guests_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Guests_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 3 "..\..\Views\Guests\Index.cshtml"
  
    ViewBag.Title = " - lista gości";
    Layout = "~/Views/Shared/_LayoutSubPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" id=\"guestsContainer\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row guest-search\"");

WriteLiteral(">\r\n");

            
            #line 11 "..\..\Views\Guests\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Guests\Index.cshtml"
               Html.RenderPartial("_Search"); 
            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"guests-actions\"");

WriteLiteral(">\r\n                <div>\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#createGroupModal\"");

WriteLiteral(" class=\"btn-simple narrow\"");

WriteLiteral(">\r\n                        STWÓRZ GRUPĘ\r\n                    </button>\r\n         " +
"           <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btnReports\"");

WriteLiteral(" class=\"btn-simple narrow\"");

WriteLiteral(">\r\n                        EKSPORTUJ GOŚCI\r\n                    </button>\r\n      " +
"          </div>\r\n                <div");

WriteLiteral(" id=\"reports\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 24 "..\..\Views\Guests\Index.cshtml"
               Write(Html.ActionLink("ZACHOWAJ OBECNĄ KOLEJNOŚĆ", "GuestsPdf", "Pdf", null, new { @class = "btn-report", target = "_blank" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 25 "..\..\Views\Guests\Index.cshtml"
               Write(Html.ActionLink("POSORTUJ WEDŁUG STATUSU", "GuestsByStatusPdf", "Pdf", null, new { @class = "btn-report", target = "_blank" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row groups-area\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"groups\"");

WriteLiteral(">\r\n\r\n            </div>\r\n        </div>\r\n");

            
            #line 34 "..\..\Views\Guests\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\Guests\Index.cshtml"
          
            Html.RenderPartial("_CreateGroup", new GroupModel());
            Html.RenderPartial("_EditGroup", new GroupModel());
            Html.RenderPartial("_ModalAnimate", new ViewDataDictionary { { "Action", "CreatePersons" }, { "Controller", "Guests" }, { "Id", "createPersonsModal" }, { "Desc", "DODAJ NOWE OSOBY" } });
            Html.RenderPartial("_ModalAnimate", new ViewDataDictionary { { "Action", "UpdatePersons" }, { "Controller", "Guests" }, { "Id", "editPersonsModal" }, { "Desc", "AKTUALIZACJA OSÓB" } });
        
            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" id=\"undoArea\"");

WriteLiteral(">\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 46 "..\..\Views\Guests\Index.cshtml"
Write(Scripts.Render("~/bundles/guests"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
