#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    #line 2 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
    using Microsoft.Owin.Security;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/_ExternalLoginsListPartial.cshtml")]
    public partial class _Views_Account__ExternalLoginsListPartial_cshtml : System.Web.Mvc.WebViewPage<AIT.WebUIComponent.Models.Account.ExternalLoginListViewModel>
    {
        public _Views_Account__ExternalLoginsListPartial_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
  
    var loginProviders = Context.GetOwinContext().Authentication.GetExternalAuthenticationTypes();

    using (Html.BeginForm("ExternalLogin", "Account", new { ReturnUrl = Model.ReturnUrl }, FormMethod.Post, new { @class = "form", id = "externalLoginForm" }))
    {
        
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                                
        foreach (AuthenticationDescription desc in loginProviders)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"submit\"");

WriteAttribute("id", Tuple.Create(" id=\"", 565), Tuple.Create("\"", 594)
            
            #line 13 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
, Tuple.Create(Tuple.Create("", 570), Tuple.Create<System.Object, System.Int32>(desc.AuthenticationType
            
            #line default
            #line hidden
, 570), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 595), Tuple.Create("\"", 663)
, Tuple.Create(Tuple.Create("", 603), Tuple.Create("form-control", 603), true)
, Tuple.Create(Tuple.Create(" ", 615), Tuple.Create("btn-external", 616), true)
            
            #line 13 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                     , Tuple.Create(Tuple.Create(" ", 628), Tuple.Create<System.Object, System.Int32>(desc.AuthenticationType.ToLower()
            
            #line default
            #line hidden
, 629), false)
);

WriteLiteral(" name=\"provider\"");

WriteAttribute("value", Tuple.Create(" value=\"", 680), Tuple.Create("\"", 712)
            
            #line 13 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                                                                                 , Tuple.Create(Tuple.Create("", 688), Tuple.Create<System.Object, System.Int32>(desc.AuthenticationType
            
            #line default
            #line hidden
, 688), false)
);

WriteLiteral(">                    \r\n                    Zaloguj z konta ");

            
            #line 14 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                               Write(desc.AuthenticationType);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </button>\r\n            </div>            \r\n");

            
            #line 17 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
        }
    }

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
