#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/EmailConfirmation.cshtml")]
    public partial class _Views_Account_EmailConfirmation_cshtml : System.Web.Mvc.WebViewPage<AIT.WebUIComponent.Models.Account.AutoLoginModel>
    {
        public _Views_Account_EmailConfirmation_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Account\EmailConfirmation.cshtml"
  
    ViewBag.Title = " - rejestracja";
    Layout = "~/Views/Shared/_LayoutSubPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <p");

WriteLiteral(" class=\"form-text\"");

WriteLiteral(">\r\n        KONTO JEST JUŻ AKTYWNE\r\n    </p>\r\n    <hr");

WriteLiteral(" class=\"separator\"");

WriteLiteral(" />\r\n</div>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"text-center page-desc\"");

WriteLiteral(">\r\n        <p>\r\n");

WriteLiteral("            ");

            
            #line 17 "..\..\Views\Account\EmailConfirmation.cshtml"
       Write(ViewBag.StatusMessage);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </p>\r\n");

            
            #line 19 "..\..\Views\Account\EmailConfirmation.cshtml"
        
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\Account\EmailConfirmation.cshtml"
         if (Model.AutoLoginEnabled)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" id=\"autoLogin\"");

WriteLiteral(">\r\n");

            
            #line 22 "..\..\Views\Account\EmailConfirmation.cshtml"
                
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Account\EmailConfirmation.cshtml"
                 using (Html.BeginForm("AutoLogin", "Account", FormMethod.Post, new { id = "autoLoginForm", role = "form" }))
                {
                    
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Account\EmailConfirmation.cshtml"
               Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Account\EmailConfirmation.cshtml"
                                            
                    
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\Account\EmailConfirmation.cshtml"
               Write(Html.HiddenFor(x => x.UserId));

            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\Account\EmailConfirmation.cshtml"
                                                  
                    
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Account\EmailConfirmation.cshtml"
               Write(Html.HiddenFor(x => x.AutoLoginEnabled));

            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Account\EmailConfirmation.cshtml"
                                                            

            
            #line default
            #line hidden
WriteLiteral("                    <p>\r\n                        Klikając w ten <a");

WriteLiteral(" id=\"btnAutoLogin\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">link</a> zostaniesz automatycznie zalogowany do serwisu.\r\n                    </" +
"p>\r\n");

            
            #line 30 "..\..\Views\Account\EmailConfirmation.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <p>\r\n                    Po upływie 30 sekund logowanie będzie mo" +
"żliwe jedynie przy użyciu panelu logowania.\r\n                </p>\r\n             " +
"   <div");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" id=\"countdown\"");

WriteLiteral("></div>\r\n                </div>\r\n            </div>\r\n");

            
            #line 38 "..\..\Views\Account\EmailConfirmation.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        \r\n        <div");

WriteLiteral(" id=\"normalLogin\"");

WriteLiteral(">\r\n            <p>\r\n                Już teraz <strong>");

            
            #line 42 "..\..\Views\Account\EmailConfirmation.cshtml"
                             Write(Html.ActionLink("zaloguj się", "Login", "Account", new { returnUrl = "/Home" }, null));

            
            #line default
            #line hidden
WriteLiteral("</strong> i zacznij korzystać z serwisu Zamiłowani.pl\r\n            </p>\r\n        " +
"</div>        \r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 49 "..\..\Views\Account\EmailConfirmation.cshtml"
Write(Scripts.Render("~/bundles/autologin"));

            
            #line default
            #line hidden
WriteLiteral("    \r\n");

});

        }
    }
}
#pragma warning restore 1591
