#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Account\Login.cshtml"
    using AIT.WebUIComponent.Models.Account;
    
    #line default
    #line hidden
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Login.cshtml")]
    public partial class _Views_Account_Login_cshtml : System.Web.Mvc.WebViewPage<SignInModel>
    {
        public _Views_Account_Login_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Account\Login.cshtml"
  
    ViewBag.Title = " - logowanie";
    Layout = "~/Views/Shared/_LayoutSubPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <p");

WriteLiteral(" class=\"form-text\"");

WriteLiteral(">\r\n        WYBIERZ METODĘ LOGOWANIA\r\n    </p>\r\n    <hr");

WriteLiteral(" class=\"separator\"");

WriteLiteral(" />\r\n</div>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-xs-12 col-sm-5\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"form-panel login-external\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-header form-header-green\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-title\"");

WriteLiteral(">\r\n                    Użyj zewnętrznego serwisu\r\n                </div>\r\n       " +
"     </div>\r\n            <div");

WriteLiteral(" class=\"form-body form-body-green\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 24 "..\..\Views\Account\Login.cshtml"
           Write(Html.Partial("_ExternalLoginsListPartial", new ExternalLoginListViewModel { ReturnUrl = ViewBag.ReturnUrl }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-xs-12 col-sm-2\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"login-or\"");

WriteLiteral(">LUB</div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-xs-12 col-sm-5\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"form-panel login-internal\"");

WriteLiteral(">\r\n            <div>\r\n                <div");

WriteLiteral(" class=\"form-header form-header-blue\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-title\"");

WriteLiteral(">\r\n                        Użyj swojego konta\r\n                    </div>\r\n      " +
"          </div>\r\n                <div");

WriteLiteral(" class=\"form-body form-body-blue\"");

WriteLiteral(">\r\n");

            
            #line 42 "..\..\Views\Account\Login.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\Account\Login.cshtml"
                     using (Ajax.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, new AjaxOptions
                    {
                        OnBegin = "loginManager.onBegin",
                        OnSuccess = "loginManager.onSuccess",
                        OnFailure = "loginManager.onFailure"
                    }, new { autocomplete = "off", @id = "loginForm" }))
                    {
                        
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Account\Login.cshtml"
                   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Account\Login.cshtml"
                                                


            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"form-inputs\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 53 "..\..\Views\Account\Login.cshtml"
                           Write(Html.TextBoxFor(m => m.Username, new { @class = "form-ctrl", placeholder = "Nazwa użytkownika" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 56 "..\..\Views\Account\Login.cshtml"
                           Write(Html.PasswordFor(m => m.Password, new { @class = "form-ctrl", placeholder = "Hasło" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n");

WriteLiteral("                        <div");

WriteLiteral(" class=\"form-checkbox\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" id=\"RememberMe\"");

WriteLiteral(" name=\"RememberMe\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" value=\"true\"");

WriteLiteral(" />\r\n                            <label");

WriteLiteral(" for=\"RememberMe\"");

WriteLiteral(">Zapamiętaj mnie</label>\r\n                        </div>\r\n");

WriteLiteral("                        <div");

WriteLiteral(" class=\"form-body-btn\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn-rounded btn-turquoise\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"icon icon-lg icon-enter\"");

WriteLiteral("></span>\r\n                            </button>\r\n                        </div>\r\n" +
"");

            
            #line 68 "..\..\Views\Account\Login.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"account-questions\"");

WriteLiteral(">\r\n                <div>");

            
            #line 72 "..\..\Views\Account\Login.cshtml"
                Write(Html.ActionLink("Nie masz konta? Utwórz konto teraz", "Register", "Account"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                <div>");

            
            #line 73 "..\..\Views\Account\Login.cshtml"
                Write(Html.ActionLink("Nie pamiętasz hasła?", "ForgotPassword", "Account"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 80 "..\..\Views\Account\Login.cshtml"
Write(Scripts.Render("~/bundles/login"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
