#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Register.cshtml")]
    public partial class _Views_Account_Register_cshtml : System.Web.Mvc.WebViewPage<AIT.WebUIComponent.Models.Account.RegisterModel>
    {
        public _Views_Account_Register_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Account\Register.cshtml"
  
    ViewBag.Title = " - rejestracja";
    Layout = "~/Views/Shared/_LayoutSubPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <p");

WriteLiteral(" class=\"form-text\"");

WriteLiteral(">\r\n        REJESTRACJA UŻYTKOWNIKA\r\n    </p>\r\n    <hr");

WriteLiteral(" class=\"separator\"");

WriteLiteral(" />\r\n</div>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form-panel\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"form-header form-header-blue\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-title\"");

WriteLiteral(">\r\n                Stwórz nowe konto\r\n            </div>\r\n        </div>\r\n       " +
" <div");

WriteLiteral(" class=\"form-body form-body-blue\"");

WriteLiteral(">\r\n");

            
            #line 21 "..\..\Views\Account\Register.cshtml"
            
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Account\Register.cshtml"
             using (Ajax.BeginForm("Register", "Account", null, new AjaxOptions
            {
                OnBegin = "registerManager.onBegin",
                OnSuccess = "registerManager.onSuccess",
                OnFailure = "registerManager.onFailure"
            }, new { @id = "registerForm" }))
            {
                
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Account\Register.cshtml"
           Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Account\Register.cshtml"
                                        


            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"form-inputs\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 32 "..\..\Views\Account\Register.cshtml"
                   Write(Html.TextBoxFor(m => m.Username, new { @class = "form-ctrl", placeholder = "Nazwa użytkownika" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 35 "..\..\Views\Account\Register.cshtml"
                   Write(Html.TextBoxFor(m => m.Email, new { @class = "form-ctrl", placeholder = "E-mail" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 36 "..\..\Views\Account\Register.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 39 "..\..\Views\Account\Register.cshtml"
                   Write(Html.PasswordFor(m => m.Password, new { @class = "form-ctrl", placeholder = "Hasło" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 40 "..\..\Views\Account\Register.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 43 "..\..\Views\Account\Register.cshtml"
                   Write(Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-ctrl", placeholder = "Powtórz hasło" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 44 "..\..\Views\Account\Register.cshtml"
                   Write(Html.ValidationMessageFor(m => m.ConfirmPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-checkbox\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"TermsAccepted\"");

WriteLiteral(" name=\"TermsAccepted\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" value=\"true\"");

WriteLiteral(" />\r\n                        <label");

WriteLiteral(" for=\"TermsAccepted\"");

WriteLiteral(">Oświadczam, że ");

            
            #line 50 "..\..\Views\Account\Register.cshtml"
                                                             Write(Html.ActionLink("REGULAMIN", "UserAgreement", "Documents", null, new { @class = "color-grey", target = "_blank" }));

            
            #line default
            #line hidden
WriteLiteral(" jest mi znany.</label>\r\n                    </div>\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"form-body-btn\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn-rounded btn-turquoise\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"icon icon-lg icon-register\"");

WriteLiteral("></span>\r\n                    </button>\r\n                </div>\r\n");

            
            #line 58 "..\..\Views\Account\Register.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 64 "..\..\Views\Account\Register.cshtml"
Write(Scripts.Render("~/bundles/register"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
