#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ResetPassword.cshtml")]
    public partial class _Views_Account_ResetPassword_cshtml : System.Web.Mvc.WebViewPage<AIT.WebUIComponent.Models.Account.ResetPasswordViewModel>
    {
        public _Views_Account_ResetPassword_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Account\ResetPassword.cshtml"
  
    ViewBag.Title = " - zmiana hasła";
    Layout = "~/Views/Shared/_LayoutSubPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <p");

WriteLiteral(" class=\"form-text\"");

WriteLiteral(">\r\n        ZMIANA HASŁA\r\n    </p>\r\n    <hr");

WriteLiteral(" class=\"separator\"");

WriteLiteral(" />\r\n</div>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form-panel\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"form-header form-header-green\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-title\"");

WriteLiteral(">\r\n                Wprowadź nowe hasło\r\n            </div>\r\n        </div>\r\n     " +
"   <div");

WriteLiteral(" class=\"form-body form-body-green\"");

WriteLiteral(">\r\n");

            
            #line 22 "..\..\Views\Account\ResetPassword.cshtml"
            
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Account\ResetPassword.cshtml"
             using (Html.BeginForm("ResetPassword", "Account", FormMethod.Post, new { id = "resetPassForm", @class = "form-reset", role = "form" }))
            {
                
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Account\ResetPassword.cshtml"
           Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Account\ResetPassword.cshtml"
                                        
                
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\Account\ResetPassword.cshtml"
           Write(Html.HiddenFor(model => model.Code));

            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\Account\ResetPassword.cshtml"
                                                    
                
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Account\ResetPassword.cshtml"
           Write(Html.HiddenFor(model => model.UserId));

            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Account\ResetPassword.cshtml"
                                                      
                

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"form-inputs\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 30 "..\..\Views\Account\ResetPassword.cshtml"
                   Write(Html.PasswordFor(m => m.Password, new { @class = "form-ctrl", placeholder = "Nowe hasło" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 31 "..\..\Views\Account\ResetPassword.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"form-ctrl-area\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 34 "..\..\Views\Account\ResetPassword.cshtml"
                   Write(Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-ctrl", placeholder = "Powtórz hasło" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 35 "..\..\Views\Account\ResetPassword.cshtml"
                   Write(Html.ValidationMessageFor(m => m.ConfirmPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");

WriteLiteral("                    ");

            
            #line 37 "..\..\Views\Account\ResetPassword.cshtml"
               Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"form-body-btn\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn-rounded btn-turquoise\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"icon icon-lg icon-save\"");

WriteLiteral("></span>\r\n                    </button>\r\n                </div>\r\n");

            
            #line 44 "..\..\Views\Account\ResetPassword.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 50 "..\..\Views\Account\ResetPassword.cshtml"
Write(Scripts.Render("~/bundles/enhance"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
