#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Pdf/_Guests.cshtml")]
    public partial class _Views_Pdf__Guests_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<AIT.WebUIComponent.Models.Pdf.PersonModel>>
    {
        public _Views_Pdf__Guests_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Pdf\_Guests.cshtml"
  
    var count = Model.Count();

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<table>\r\n    <thead>\r\n        <tr>\r\n            <th");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(" style=\"font-size: 22px\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 11 "..\..\Views\Pdf\_Guests.cshtml"
           Write(ViewData["GroupName"]);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 11 "..\..\Views\Pdf\_Guests.cshtml"
                                   Write(count > 0 ? string.Format("({0})", count) : string.Empty);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </th>\r\n        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 16 "..\..\Views\Pdf\_Guests.cshtml"
        
            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\Pdf\_Guests.cshtml"
         if (count > 0) { 
            foreach (var person in Model)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 21 "..\..\Views\Pdf\_Guests.cshtml"
                   Write(person.FullName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 24 "..\..\Views\Pdf\_Guests.cshtml"
                   Write(person.Phone);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                </tr>\r\n");

            
            #line 27 "..\..\Views\Pdf\_Guests.cshtml"
            }
        }
        else {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">Brak</td>\r\n            </tr>\r\n");

            
            #line 33 "..\..\Views\Pdf\_Guests.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
