#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Pdf/GuestsByStatusPdf.cshtml")]
    public partial class _Views_Pdf_GuestsByStatusPdf_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<AIT.WebUIComponent.Models.Pdf.GroupByStatusModel>>
    {
        public _Views_Pdf_GuestsByStatusPdf_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Pdf\GuestsByStatusPdf.cshtml"
  
    ViewBag.Title = "Guests by status pdf";
    Layout = "~/Views/Shared/_PdfLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>\r\n    Osoby zaakceptowane\r\n</h2>\r\n");

            
            #line 11 "..\..\Views\Pdf\GuestsByStatusPdf.cshtml"
 foreach (var group in Model)
{
    Html.RenderPartial("_Guests", group.PersonsAccepted, new ViewDataDictionary { { "GroupName", group.Name } });
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>\r\n    Osoby niepotwierdzone\r\n</h2>\r\n");

            
            #line 19 "..\..\Views\Pdf\GuestsByStatusPdf.cshtml"
 foreach (var group in Model)
{
    Html.RenderPartial("_Guests", group.PersonsUnconfirmed, new ViewDataDictionary { { "GroupName", group.Name } });  
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>\r\n    Osoby odrzucone\r\n</h2> \r\n");

            
            #line 27 "..\..\Views\Pdf\GuestsByStatusPdf.cshtml"
 foreach (var group in Model)
{        
    Html.RenderPartial("_Guests", group.PersonsDeclined, new ViewDataDictionary { { "GroupName", group.Name } });
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
