#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Undo/_Undo.cshtml")]
    public partial class _Views_Undo__Undo_cshtml : System.Web.Mvc.WebViewPage<AIT.WebUIComponent.Models.Undo.UndoModel>
    {
        public _Views_Undo__Undo_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" id=\"undoInfo\"");

WriteLiteral(" class=\"info-fixed-bottom\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n");

            
            #line 5 "..\..\Views\Undo\_Undo.cshtml"
        
            
            #line default
            #line hidden
            
            #line 5 "..\..\Views\Undo\_Undo.cshtml"
         using (Ajax.BeginForm("Undo", "Undo", new { key = Model.Key }, null))
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"undo-area\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"undo-desc\"");

WriteLiteral(">\r\n                        <span>");

            
            #line 10 "..\..\Views\Undo\_Undo.cshtml"
                         Write(Model.Description);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"udno-actions\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn-rounded btn-turquoise\"");

WriteLiteral(" title=\"Cofnij zmianę\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"icon icon-lg icon-undo\"");

WriteLiteral("></span>\r\n                        </button>\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn-rounded btn-dismiss btn-close-undo\"");

WriteLiteral(" title=\"Zamknij panel\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"icon icon-lg icon-cancel\"");

WriteLiteral("></span>\r\n                        </button>\r\n                    </div>\r\n        " +
"        </div>\r\n            </div>\r\n");

            
            #line 22 "..\..\Views\Undo\_Undo.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
