#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 2 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModel.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AIT.WebUtilities.Helpers;
    using MvcSiteMapProvider.Web.Html;
    
    #line 3 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModel.cshtml"
    using MvcSiteMapProvider.Web.Html.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/SiteMapNodeModel.cshtml")]
    public partial class _Views_Shared_DisplayTemplates_SiteMapNodeModel_cshtml_ : System.Web.Mvc.WebViewPage<MvcSiteMapProvider.Web.Html.Models.SiteMapNodeModel>
    {
        public _Views_Shared_DisplayTemplates_SiteMapNodeModel_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n");

            
            #line 5 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModel.cshtml"
 if (Model.IsCurrentNode && Model.SourceMetadata["HtmlHelper"].ToString() != "MvcSiteMapProvider.Web.Html.MenuHelper")  { 

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 6 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModel.cshtml"
     Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("\n");

            
            #line 7 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModel.cshtml"
} else if (Model.IsClickable) { 

            
            #line default
            #line hidden
WriteLiteral("    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 321), Tuple.Create("\"", 338)
            
            #line 8 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModel.cshtml"
, Tuple.Create(Tuple.Create("", 328), Tuple.Create<System.Object, System.Int32>(Model.Url
            
            #line default
            #line hidden
, 328), false)
);

WriteLiteral(">");

            
            #line 8 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModel.cshtml"
                    Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</a>\n");

            
            #line 9 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModel.cshtml"
} else { 

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 10 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModel.cshtml"
     Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("\n");

            
            #line 11 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModel.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
